### ISSUE TITLE
Semaphore service crashing after update to v2.8.75

### ISSUE THREAD

**Issue by Sinitronics** [ansible-semaphore/semaphore#1095]
After upgrading to v2.8.75 the semaphore service crashes when trying to run any jobs.

System:
debian_version: 11.5
uname: Linux ansible.eli.int 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

Package used for upgrade: semaphore_2.8.75_linux_amd64.deb

Journal output:

```
Nov 19 21:32:05 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:05Z" level=info msg="Task 2147483450 added to queue"
Nov 19 21:32:08 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:08Z" level=info msg="Set resource locker with TaskRunner 2147483450"
Nov 19 21:32:09 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:09Z" level=warning msg="read |0: file already closed" error="Failed to read TaskRunner output"
Nov 19 21:32:09 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:09Z" level=info msg="Stopped preparing TaskRunner 2147483450"
Nov 19 21:32:09 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:09Z" level=info msg="Release resource locker with TaskRunner 2147483450"
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:13Z" level=info msg="Set resource locker with TaskRunner 2147483450"
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:13Z" level=info msg="Task 2147483450 removed from queue"
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:13Z" level=info msg="Stopped running TaskRunner 2147483450"
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: time="2022-11-19T21:32:13Z" level=info msg="Release resource locker with TaskRunner 2147483450"
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         panic: runtime error: invalid memory address or nil pointer dereference
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1f0 pc=0x82e998]
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: goroutine 71 [running]:
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: go.etcd.io/bbolt.(*DB).beginRWTx(0x3?)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:581 +0x38
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: go.etcd.io/bbolt.(*DB).Begin(0x0?, 0x8?)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:536 +0x1d
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: go.etcd.io/bbolt.(*DB).Update(0x40eea5?, 0xc001934d38)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:672 +0x3e
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).updateObject(0xc000003a00?, 0x4?, {{0x9d4240, 0x4}, {0x1fc7da0, 0x9bdb60}, 0x1, {0x0, 0x0}, {0x9d36c8, ...}, ...}, ...)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:404 +0xba
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).UpdateTask(0x60?, {0x7fffff3a, 0x1, 0x1, {0x9d785e, 0x7}, 0x0, 0x0, 0x0, {0x0, ...}, ...})
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/db/bolt/task.go:20 +0xac
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).updateStatus(0xc00016e100)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/services/tasks/runner.go:111 +0x5f8
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).run.func1()
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/services/tasks/runner.go:245 +0x185
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: panic({0x94fa20, 0x22dc7e0})
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x207
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: go.etcd.io/bbolt.(*DB).beginRWTx(0xe?)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:581 +0x38
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: go.etcd.io/bbolt.(*DB).Begin(0x0?, 0x70?)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:536 +0x1d
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: go.etcd.io/bbolt.(*DB).Update(0x40eea5?, 0xc0019355a0)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:672 +0x3e
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).updateObject(0xc000003a00?, 0x4?, {{0x9d4240, 0x4}, {0x1fc7da0, 0x9bdb60}, 0x1, {0x0, 0x0}, {0x9d36c8, ...}, ...}, ...)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:404 +0xba
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).UpdateTask(0xc001243bc0?, {0x7fffff3a, 0x1, 0x1, {0x9d785e, 0x7}, 0x0, 0x0, 0x0, {0x0, ...}, ...})
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/db/bolt/task.go:20 +0xac
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).updateStatus(0xc00016e100)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/services/tasks/runner.go:111 +0x5f8
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).setStatus(0xc00016e100, {0x9d785e?, 0x40f0fd?})
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/services/tasks/runner.go:81 +0xc5
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).run(0xc00016e100)
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/services/tasks/runner.go:258 +0x14a
Nov 19 21:32:13 ansible.eli.int semaphore[1442]: created by github.com/ansible-semaphore/semaphore/services/tasks.(*TaskPool).Run
Nov 19 21:32:13 ansible.eli.int semaphore[1442]:         /home/runner/work/semaphore/semaphore/services/tasks/pool.go:158 +0x4f6
Nov 19 21:32:13 ansible.eli.int systemd[1]: semaphore.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit semaphore.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 2.
Nov 19 21:32:13 ansible.eli.int systemd[1]: semaphore.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit semaphore.service has entered the 'failed' state with result 'exit-code'.
Nov 19 21:32:13 ansible.eli.int systemd[1]: semaphore.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ Automatic restarting of the unit semaphore.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Nov 19 21:32:13 ansible.eli.int systemd[1]: Stopped Semaphore Ansible.
░░ Subject: A stop job for unit semaphore.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A stop job for unit semaphore.service has finished.
░░
░░ The job identifier is 657 and the job result is done.
Nov 19 21:32:13 ansible.eli.int systemd[1]: Started Semaphore Ansible.
░░ Subject: A start job for unit semaphore.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit semaphore.service has finished successfully.
░░
░░ The job identifier is 657.
Nov 19 21:32:14 ansible.eli.int semaphore[1468]: BoltDB /data/semaphore/database.boltdb
Nov 19 21:32:14 ansible.eli.int semaphore[1468]: Tmp Path (projects home) /data/semaphore/playbooks
Nov 19 21:32:14 ansible.eli.int semaphore[1468]: Semaphore v2.8.75
Nov 19 21:32:14 ansible.eli.int semaphore[1468]: Interface
Nov 19 21:32:14 ansible.eli.int semaphore[1468]: Port :3000
Nov 19 21:32:14 ansible.eli.int semaphore[1468]: Server is running
```

Downgraded back to v2.8.74 and all is working ok.

**Comment by fiftin** [comment]
Hi @Sinitronics 
Fixing in progress, will be released today. Thank you!

**Comment by fiftin** [comment]
@Sinitronics Please test pre-release https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.77

**Comment by Sinitronics** [comment]
> @Sinitronics Please test pre-release https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.77

@fiftin confirmed all working, thank you for the quick fix
