### ISSUE TITLE
Unexpecetd panic error when calling /api/project/1/tasks/last endpoint

### ISSUE THREAD

**Issue by dorinand** [ansible-semaphore/semaphore#1168]
I am running Semaphore with default configuration:
```
services:
  semaphore:
    ports:
      - 3001:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
```

When I call list of tasks (with or without username and password) I receive an error:
```
curl -u admin:changeme -X 'GET' \
  'http://localhost:3001/api/project/1/tasks/last' \
  -H 'accept: application/json'
curl: (52) Empty reply from server
```

Logs from applications:
```
2023/02/16 00:12:54 http: panic serving 172.21.0.1:64902: interface conversion: interface {} is nil, not *db.User
goroutine 36 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xb8
panic({0x4f2680, 0x400054efc0})
	/usr/local/go/src/runtime/panic.go:844 +0x260
github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1({0x1b63690, 0x400054c620}, 0x1e8eb60?)
	/go/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:14 +0x308
net/http.HandlerFunc.ServeHTTP(0x1b63690?, {0x1b63690?, 0x400054c620?}, 0x528760?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/api.authentication.func1({0x1b63690, 0x400054c620}, 0x1?)
	/go/src/github.com/ansible-semaphore/semaphore/api/auth.go:109 +0x5c
net/http.HandlerFunc.ServeHTTP(0x52ea40?, {0x1b63690?, 0x400054c620?}, 0xc?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1({0x1b63690, 0x400054c620}, 0x0?)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:35 +0xf0
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x400054c620?}, 0x40009994b8?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1.1()
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:26 +0x38
github.com/ansible-semaphore/semaphore/db.StoreSession({0x1b66e18, 0x40001a2f60}, {0x4000028680, 0x19}, 0x4000999658)
	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:336 +0x64
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1b63690, 0x400054c620}, 0x400057a300)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0xd8
net/http.HandlerFunc.ServeHTTP(0x400057a300?, {0x1b63690?, 0x400054c620?}, 0x514b60?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1b63690, 0x400054c620}, 0x400057a300?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:67 +0x104
net/http.HandlerFunc.ServeHTTP(0xffffb75d4f18?, {0x1b63690?, 0x400054c620?}, 0x400054ab40?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x1b63690, 0x400054c620}, 0x400054aab0?)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x84
net/http.HandlerFunc.ServeHTTP(0x400057a200?, {0x1b63690?, 0x400054c620?}, 0x55c780?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.(*Router).ServeHTTP(0x40001f6180, {0x1b63690, 0x400054c620}, 0x4000130100)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1d8
github.com/gorilla/handlers.ProxyHeaders.func1({0x1b63690, 0x400054c620}, 0x4000130100)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x154
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x400054c620?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1({0x1b63690?, 0x400054c620?}, 0x4000130100?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x114
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x400054c620?}, 0x4ecec?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x400012a090?}, {0x1b63690, 0x400054c620}, 0x4000130100)
	/usr/local/go/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x400012c000, {0x1b63a98, 0x400068c180})
	/usr/local/go/src/net/http/server.go:1966 +0x550
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x448
```

Then, I cannot show Dashboard section from UI - the page is empty.

When I restart the container, everything works fine, DB is not corrupted. 
If I call it from webserver, it works fine.

**Comment by dorinand** [comment]
So since the issue I am able to run tasks but with an error:
```
time="2023-02-16T00:30:35Z" level=info msg="Task 2147483614 added to queue"
2023/02/16 00:30:35 http: panic serving 172.21.0.1:62180: Connection /api/project/1/tasks/last already exists
goroutine 161 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xb8
panic({0x4dc200, 0x4001dd47e0})
	/usr/local/go/src/runtime/panic.go:844 +0x260
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0x400016af90, {0x4001dc1860, 0x19})
	/go/src/github.com/ansible-semaphore/semaphore/db/bolt/BoltDb.go:85 +0x354
github.com/ansible-semaphore/semaphore/db.StoreSession({0x1b66e18, 0x400016af90}, {0x4001dc1860, 0x19}, 0x4001911658)
	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:333 +0x58
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1b63690, 0x4001d87a40}, 0x4001ac3400)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0xd8
net/http.HandlerFunc.ServeHTTP(0x4001ac3400?, {0x1b63690?, 0x4001d87a40?}, 0x514b60?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1b63690, 0x4001d87a40}, 0x4001ac3400?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:67 +0x104
net/http.HandlerFunc.ServeHTTP(0xffffbcdbdf18?, {0x1b63690?, 0x4001d87a40?}, 0x4002210090?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x1b63690, 0x4001d87a40}, 0x4002210000?)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x84
net/http.HandlerFunc.ServeHTTP(0x4001ac3300?, {0x1b63690?, 0x4001d87a40?}, 0x55c780?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002ce180, {0x1b63690, 0x4001d87a40}, 0x4001ac2f00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1d8
github.com/gorilla/handlers.ProxyHeaders.func1({0x1b63690, 0x4001d87a40}, 0x4001ac2f00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x154
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87a40?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1({0x1b63690?, 0x4001d87a40?}, 0x4001ac2f00?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x114
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87a40?}, 0x4ecec?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x400124a4b0?}, {0x1b63690, 0x4001d87a40}, 0x4001ac2f00)
	/usr/local/go/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x4000570b40, {0x1b63a98, 0x40006b2180})
	/usr/local/go/src/net/http/server.go:1966 +0x550
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x448
2023/02/16 00:30:35 http: panic serving 172.21.0.1:62300: Connection /api/project/1/tasks/2147483614 already exists
goroutine 188 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xb8
panic({0x4dc200, 0x40021c6b60})
	/usr/local/go/src/runtime/panic.go:844 +0x260
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0x400016af90, {0x40022c0c00, 0x1f})
	/go/src/github.com/ansible-semaphore/semaphore/db/bolt/BoltDb.go:85 +0x354
github.com/ansible-semaphore/semaphore/db.StoreSession({0x1b66e18, 0x400016af90}, {0x40022c0c00, 0x1f}, 0x4000d51658)
	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:333 +0x58
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1b63690, 0x4001d87b20}, 0x4001ac3600)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0xd8
net/http.HandlerFunc.ServeHTTP(0x4001ac3600?, {0x1b63690?, 0x4001d87b20?}, 0x514b60?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1b63690, 0x4001d87b20}, 0x4001ac3600?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:67 +0x104
net/http.HandlerFunc.ServeHTTP(0xffffbcdbdf18?, {0x1b63690?, 0x4001d87b20?}, 0x4002210240?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x1b63690, 0x4001d87b20}, 0x40022101b0?)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x84
net/http.HandlerFunc.ServeHTTP(0x4001ac3500?, {0x1b63690?, 0x4001d87b20?}, 0x55c780?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002ce180, {0x1b63690, 0x4001d87b20}, 0x4000e65100)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1d8
github.com/gorilla/handlers.ProxyHeaders.func1({0x1b63690, 0x4001d87b20}, 0x4000e65100)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x154
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87b20?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1({0x1b63690?, 0x4001d87b20?}, 0x4000e65100?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x114
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87b20?}, 0x4ecec?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x4001aa14d0?}, {0x1b63690, 0x4001d87b20}, 0x4000e65100)
	/usr/local/go/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x4000109c20, {0x1b63a98, 0x40006b2180})
	/usr/local/go/src/net/http/server.go:1966 +0x550
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x448
2023/02/16 00:30:35 http: panic serving 172.21.0.1:62304: Connection /api/project/1/tasks/2147483614 already exists
goroutine 197 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xb8
panic({0x4dc200, 0x40007d4ef0})
	/usr/local/go/src/runtime/panic.go:844 +0x260
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0x400016af90, {0x400287d960, 0x1f})
	/go/src/github.com/ansible-semaphore/semaphore/db/bolt/BoltDb.go:85 +0x354
github.com/ansible-semaphore/semaphore/db.StoreSession({0x1b66e18, 0x400016af90}, {0x400287d960, 0x1f}, 0x400190d658)
	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:333 +0x58
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1b63690, 0x4000bee380}, 0x400056ec00)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0xd8
net/http.HandlerFunc.ServeHTTP(0x400056ec00?, {0x1b63690?, 0x4000bee380?}, 0x514b60?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1b63690, 0x4000bee380}, 0x400056ec00?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:67 +0x104
net/http.HandlerFunc.ServeHTTP(0xffffbcdbda68?, {0x1b63690?, 0x4000bee380?}, 0x400052a990?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x1b63690, 0x4000bee380}, 0x400052a900?)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x84
net/http.HandlerFunc.ServeHTTP(0x400056eb00?, {0x1b63690?, 0x4000bee380?}, 0x55c780?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002ce180, {0x1b63690, 0x4000bee380}, 0x4000e64e00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1d8
github.com/gorilla/handlers.ProxyHeaders.func1({0x1b63690, 0x4000bee380}, 0x4000e64e00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x154
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4000bee380?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1({0x1b63690?, 0x4000bee380?}, 0x4000e64e00?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x114
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4000bee380?}, 0x4ecec?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x400112fe00?}, {0x1b63690, 0x4000bee380}, 0x4000e64e00)
	/usr/local/go/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x400069b040, {0x1b63a98, 0x40006b2180})
	/usr/local/go/src/net/http/server.go:1966 +0x550
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x448
2023/02/16 00:30:35 http: panic serving 172.21.0.1:62564: Connection /api/project/1/tasks/last already exists
goroutine 232 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xb8
panic({0x4dc200, 0x4001dd4870})
	/usr/local/go/src/runtime/panic.go:844 +0x260
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0x400016af90, {0x4001dc1900, 0x19})
	/go/src/github.com/ansible-semaphore/semaphore/db/bolt/BoltDb.go:85 +0x354
github.com/ansible-semaphore/semaphore/db.StoreSession({0x1b66e18, 0x400016af90}, {0x4001dc1900, 0x19}, 0x400055b658)
	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:333 +0x58
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1b63690, 0x4001d87c00}, 0x4001ac3900)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0xd8
net/http.HandlerFunc.ServeHTTP(0x4001ac3900?, {0x1b63690?, 0x4001d87c00?}, 0x514b60?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1b63690, 0x4001d87c00}, 0x4001ac3900?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:67 +0x104
net/http.HandlerFunc.ServeHTTP(0xffffbcdbdf18?, {0x1b63690?, 0x4001d87c00?}, 0x4002210480?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x1b63690, 0x4001d87c00}, 0x40022103f0?)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x84
net/http.HandlerFunc.ServeHTTP(0x4001ac3800?, {0x1b63690?, 0x4001d87c00?}, 0x55c780?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002ce180, {0x1b63690, 0x4001d87c00}, 0x4001ac3700)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1d8
github.com/gorilla/handlers.ProxyHeaders.func1({0x1b63690, 0x4001d87c00}, 0x4001ac3700)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x154
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87c00?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1({0x1b63690?, 0x4001d87c00?}, 0x4001ac3700?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x114
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87c00?}, 0x4ecec?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x400220c6c0?}, {0x1b63690, 0x4001d87c00}, 0x4001ac3700)
	/usr/local/go/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x40002deaa0, {0x1b63a98, 0x40006b2180})
	/usr/local/go/src/net/http/server.go:1966 +0x550
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x448
2023/02/16 00:30:35 http: panic serving 172.21.0.1:62566: Connection /api/project/1/tasks/2147483614 already exists
goroutine 108 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xb8
panic({0x4dc200, 0x4001dd48c0})
	/usr/local/go/src/runtime/panic.go:844 +0x260
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0x400016af90, {0x4001dc1960, 0x1f})
	/go/src/github.com/ansible-semaphore/semaphore/db/bolt/BoltDb.go:85 +0x354
github.com/ansible-semaphore/semaphore/db.StoreSession({0x1b66e18, 0x400016af90}, {0x4001dc1960, 0x1f}, 0x400055b658)
	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:333 +0x58
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1b63690, 0x4001d87ce0}, 0x4001ac3b00)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0xd8
net/http.HandlerFunc.ServeHTTP(0x4001ac3b00?, {0x1b63690?, 0x4001d87ce0?}, 0x514b60?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1b63690, 0x4001d87ce0}, 0x4001ac3b00?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:67 +0x104
net/http.HandlerFunc.ServeHTTP(0xffffbcdbdf18?, {0x1b63690?, 0x4001d87ce0?}, 0x40022106c0?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x1b63690, 0x4001d87ce0}, 0x4002210630?)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x84
net/http.HandlerFunc.ServeHTTP(0x4001ac3a00?, {0x1b63690?, 0x4001d87ce0?}, 0x55c780?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002ce180, {0x1b63690, 0x4001d87ce0}, 0x400056ed00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1d8
github.com/gorilla/handlers.ProxyHeaders.func1({0x1b63690, 0x4001d87ce0}, 0x400056ed00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x154
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87ce0?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1({0x1b63690?, 0x4001d87ce0?}, 0x400056ed00?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x114
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4001d87ce0?}, 0x4ecec?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x4000bf0d50?}, {0x1b63690, 0x4001d87ce0}, 0x400056ed00)
	/usr/local/go/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x40002f00a0, {0x1b63a98, 0x40006b2180})
	/usr/local/go/src/net/http/server.go:1966 +0x550
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x448
2023/02/16 00:30:35 http: panic serving 172.21.0.1:62568: Connection /api/project/1/tasks/2147483614 already exists
goroutine 235 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xb8
panic({0x4dc200, 0x40007d4f50})
	/usr/local/go/src/runtime/panic.go:844 +0x260
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0x400016af90, {0x400287d9c0, 0x1f})
	/go/src/github.com/ansible-semaphore/semaphore/db/bolt/BoltDb.go:85 +0x354
github.com/ansible-semaphore/semaphore/db.StoreSession({0x1b66e18, 0x400016af90}, {0x400287d9c0, 0x1f}, 0x4002397658)
	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:333 +0x58
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1b63690, 0x4000bee460}, 0x400056f200)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0xd8
net/http.HandlerFunc.ServeHTTP(0x400056f200?, {0x1b63690?, 0x4000bee460?}, 0x514b60?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1b63690, 0x4000bee460}, 0x400056f200?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:67 +0x104
net/http.HandlerFunc.ServeHTTP(0xffffbcdbda68?, {0x1b63690?, 0x4000bee460?}, 0x400052abd0?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x1b63690, 0x4000bee460}, 0x400052ab40?)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x84
net/http.HandlerFunc.ServeHTTP(0x400056f000?, {0x1b63690?, 0x4000bee460?}, 0x55c780?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002ce180, {0x1b63690, 0x4000bee460}, 0x4001ac3c00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1d8
github.com/gorilla/handlers.ProxyHeaders.func1({0x1b63690, 0x4000bee460}, 0x4001ac3c00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x154
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4000bee460?}, 0xffffffffffffffff?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1({0x1b63690?, 0x4000bee460?}, 0x4001ac3c00?)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x114
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1b63690?, 0x4000bee460?}, 0x4ecec?)
	/usr/local/go/src/net/http/server.go:2084 +0x3c
net/http.serverHandler.ServeHTTP({0x400220cc00?}, {0x1b63690, 0x4000bee460}, 0x4001ac3c00)
	/usr/local/go/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x40002dec80, {0x1b63a98, 0x40006b2180})
	/usr/local/go/src/net/http/server.go:1966 +0x550
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x448
time="2023-02-16T00:30:36Z" level=info msg="Set resource locker with TaskRunner 2147483614"
```
