### ISSUE TITLE
Unable to run tasks: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by dougmaitelli** [ansible-semaphore/semaphore#1232]
This is a fresh new install of semaphore, am able to run it and configure everything, however, when I try to trigger the task this happens:

```
BoltDB /root/database.boltdb
Tmp Path (projects home) /srv/semaphore
Semaphore v2.8.75
Interface 
Port :3000
Server is running
INFO[0042] Task 2147483646 added to queue               
INFO[0045] Set resource locker with TaskRunner 2147483646 
WARN[0046] read |0: file already closed                  error="Failed to read TaskRunner output"
WARN[0046] read |0: file already closed                  error="Failed to read TaskRunner output"
WARN[0046] read |0: file already closed                  error="Failed to read TaskRunner output"
WARN[0046] read |0: file already closed                  error="Failed to read TaskRunner output"
INFO[0046] Stopped preparing TaskRunner 2147483646      
INFO[0046] Release resource locker with TaskRunner 2147483646 
INFO[0050] Set resource locker with TaskRunner 2147483646 
INFO[0050] Task 2147483646 removed from queue           
INFO[0050] Stopped running TaskRunner 2147483646        
INFO[0050] Release resource locker with TaskRunner 2147483646 
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1f0 pc=0x82e998]

goroutine 61 [running]:
go.etcd.io/bbolt.(*DB).beginRWTx(0x3?)
        /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:581 +0x38
go.etcd.io/bbolt.(*DB).Begin(0x0?, 0x8?)
        /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:536 +0x1d
go.etcd.io/bbolt.(*DB).Update(0x40eea5?, 0xc00075ad38)
        /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:672 +0x3e
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).updateObject(0xc000092680?, 0x4?, {{0x9d4240, 0x4}, {0x1fc7da0, 0x9bdb60}, 0x1, {0x0, 0x0}, {0x9d36c8, ...}, ...}, ...)
        /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:404 +0xba
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).UpdateTask(0x48?, {0x7ffffffe, 0x1, 0x1, {0x9d785e, 0x7}, 0x0, 0x0, 0x0, {0x0, ...}, ...})
        /home/runner/work/semaphore/semaphore/db/bolt/task.go:20 +0xac
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).updateStatus(0xc00013f600)
        /home/runner/work/semaphore/semaphore/services/tasks/runner.go:111 +0x5f8
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).run.func1()
        /home/runner/work/semaphore/semaphore/services/tasks/runner.go:245 +0x185
panic({0x94fa20, 0x22dc7e0})
        /opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x207
go.etcd.io/bbolt.(*DB).beginRWTx(0xe?)
        /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:581 +0x38
go.etcd.io/bbolt.(*DB).Begin(0x0?, 0x70?)
        /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:536 +0x1d
go.etcd.io/bbolt.(*DB).Update(0x40eea5?, 0xc00075b5a0)
        /home/runner/work/semaphore/semaphore/vendor/go.etcd.io/bbolt/db.go:672 +0x3e
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).updateObject(0xc000092680?, 0x4?, {{0x9d4240, 0x4}, {0x1fc7da0, 0x9bdb60}, 0x1, {0x0, 0x0}, {0x9d36c8, ...}, ...}, ...)
        /home/runner/work/semaphore/semaphore/db/bolt/BoltDb.go:404 +0xba
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).UpdateTask(0x100c001270f50?, {0x7ffffffe, 0x1, 0x1, {0x9d785e, 0x7}, 0x0, 0x0, 0x0, {0x0, ...}, ...})
        /home/runner/work/semaphore/semaphore/db/bolt/task.go:20 +0xac
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).updateStatus(0xc00013f600)
        /home/runner/work/semaphore/semaphore/services/tasks/runner.go:111 +0x5f8
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).setStatus(0xc00013f600, {0x9d785e?, 0xc000031b02?})
        /home/runner/work/semaphore/semaphore/services/tasks/runner.go:81 +0xc5
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).run(0xc00013f600)
        /home/runner/work/semaphore/semaphore/services/tasks/runner.go:258 +0x14a
created by github.com/ansible-semaphore/semaphore/services/tasks.(*TaskPool).Run
        /home/runner/work/semaphore/semaphore/services/tasks/pool.go:158 +0x4f6
```

**Comment by ghost** [comment]
same here, as per [Issue 1095](https://github.com/ansible-semaphore/semaphore/issues/1095) an upgrade to v2.8.77 should sort out this issue. Will test now and advise.

**Comment by dougmaitelli** [comment]
I actually tested this again last week after upgrading everything to latest versions and the issue was resolved but forgot to close this issue
