### ISSUE TITLE
Invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by popoyorc** [ansible-semaphore/semaphore#129]
I have managed to run `make.sh watch` but when running tasks this error is thrown.

```
GIN] 2016/06/15 - 18:11:09 | 200 |    5.494925ms | 10.8.0.7 |   GET     /api/project/1/environment
[GIN] 2016/06/15 - 18:11:09 | 200 |    5.085389ms | 10.8.0.7 |   GET     /api/project/1/templates
[GIN] 2016/06/15 - 18:11:14 | 200 |     146.543µs | 10.8.0.7 |   GET     /public/html/projects/createTaskModal.html
&{{3 1 waiting false   {63601582276 844783319 0xf3bbc0} <nil> <nil>} {0 0 0 0 0 <nil>  <nil> false} {0   <nil> <nil> <nil>} {0  0  <nil> {0   <nil> <nil> <nil>} <nil> {0   <nil> <nil> <nil>} } {0  0  0 {0   <nil> <nil> <nil>}} {0  0 <nil> } [] 1}
[GIN] 2016/06/15 - 18:11:16 | 201 |   11.598427ms | 10.8.0.7 |   POST    /api/project/1/tasks
[1]
Stopped running tasks
[GIN] 2016/06/15 - 18:11:16 | 200 |      69.715µs | 10.8.0.7 |   GET     /public/html/projects/taskModal.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4d48d2]

goroutine 24 [running]:
panic(0xae6da0, 0xc82000a120)
	/root/golang/go/src/runtime/panic.go:481 +0x3e6
github.com/ansible-semaphore/semaphore/api/tasks.(*task).installKey(0xc8204d6000, 0x1, 0xc82043bfa4, 0x4, 0xc82043bfa8, 0x3, 0xc82043bfb0, 0xc82043bfc0, 0x0, 0x0, ...)
	/root/golang/ansible-semaphore/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:210 +0x142
github.com/ansible-semaphore/semaphore/api/tasks.(*task).run(0xc8204d6000)
	/root/golang/ansible-semaphore/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:88 +0x571
created by github.com/ansible-semaphore/semaphore/api/tasks.(*taskPool).run
	/root/golang/ansible-semaphore/src/github.com/ansible-semaphore/semaphore/api/tasks/pool.go:32 +0x1d6
2016/06/15 18:11:16 notifying bugsnag: runtime error: invalid memory address or nil pointer dereference
2016/06/15 18:11:16 bugsnag.Notify: not notifying in development
exit status 2
(error exit: exit status 1)
```

**Comment by matejkramny** [comment]
Code suggests the ssh `secret` was left empty (and is `nil`)

**Comment by popoyorc** [comment]
Thanks mate, I just added the private key to the key store.

**Comment by matejkramny** [comment]
Np, i've added checks to prevent this kind of thing.
