### ISSUE TITLE
Couldnt' save Key Store - Request failed with status code 400 

### ISSUE THREAD

**Issue by KingJim1984** [ansible-semaphore/semaphore#1338]
Hello I use semaphore:v2.8.90. If I save a key store login or ssh key. I get the following error message

> ![ansible_error](https://github.com/ansible-semaphore/semaphore/assets/121956934/c1d6f7ea-b0b2-4db4-82b7-d06b02dd7482)

> time="2023-07-12T09:18:53Z" level=error msg="crypto/aes: invalid key size 48"
> goroutine 49 [running]:
> runtime/debug.Stack()
> /usr/local/go/src/runtime/debug/stack.go:24 +0x65
> runtime/debug.PrintStack()
> /usr/local/go/src/runtime/debug/stack.go:16 +0x19
> github.com/ansible-semaphore/semaphore/api/helpers.WriteError({0x2298c58, 0xc0009a82a0}, {0x2294720?, 0x26a6620?})
> /go/src/github.com/ansible-semaphore/semaphore/api/helpers/helpers.go:92 +0x1ae
> github.com/ansible-semaphore/semaphore/api/projects.UpdateKey({0x2298c58, 0xc0009a82a0}, 0xc0008fb178?)
> /go/src/github.com/ansible-semaphore/semaphore/api/projects/keys.go:144 +0x51c
> net/http.HandlerFunc.ServeHTTP(0xc0004fc500?, {0x2298c58?, 0xc0009a82a0?}, 0xbbac20?)
> /usr/local/go/src/net/http/server.go:2109 +0x2f
> github.com/ansible-semaphore/semaphore/api/projects.KeyMiddleware.func1({0x2298c58, 0xc0009a82a0}, 0x22908e0?)
> /go/src/github.com/ansible-semaphore/semaphore/api/projects/keys.go:29 +0x342
> net/http.HandlerFunc.ServeHTTP(0xc0008fb2a8?, {0x2298c58?, 0xc0009a82a0?}, 0x8?)
> /usr/local/go/src/net/http/server.go:2109 +0x2f
> github.com/ansible-semaphore/semaphore/api/projects.GetMustCanMiddlewareFor.func1.1({0x2298c58, 0xc0009a82a0}, 0xc0004fc500)
> /go/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:73 +0x31a
> net/http.HandlerFunc.ServeHTTP(0xc0004fc500?, {0x2298c58?, 0xc0009a82a0?}, 0xba02e0?)
> /usr/local/go/src/net/http/server.go:2109 +0x2f
> github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1({0x2298c58, 0xc0009a82a0}, 0x0?)
> /go/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:42 +0x3bb
> net/http.HandlerFunc.ServeHTTP(0x2298c58?, {0x2298c58?, 0xc0009a82a0?}, 0x280000c000100000?)

**Comment by ansibleguy** [comment]
Greetings.

Looks a little like the [secret used to encrypt your keys](https://docs.ansible-semaphore.com/administration-guide/security#database-encryption) is invalid.
Can you try to change it? (save the previous one if you have existing keys)

\- AnsibleGuy

**Comment by ansibleguy** [comment]
Also: related to https://github.com/ansible-semaphore/semaphore/issues/1264

**Comment by ChristianHeimke** [comment]
I had the same issue and found the solution in the [installation guide](https://docs.ansible-semaphore.com/administration-guide/installation):

`SEMAPHORE_ACCESS_KEY_ENCRYPTION`  key for encrypting access keys in database. It must be generated by using the following command: `head -c32 /dev/urandom | base64`.

After generating a new `SEMAPHORE_ACCESS_KEY_ENCRYPTION` and encrypted it with base64, I could save private keys and passwords.
