### ISSUE TITLE
setup with postgres documentation lacking

### ISSUE THREAD

**Issue by reukiodo** [ansible-semaphore/semaphore#1578]
Documentation is lacking on any necessary manual steps and setup doesn't seem to take care of any actual setup.
```
dnf -y install semaphore postgresql-server
# from here it's all guess work ... where is the documentation for full setup from scratch?
postgresql-setup --initdb
# default (at least on RHEL9) seems to be extremely restrictive and doesn't allow password pgsql login
echo "local   all             all                                     md5" >> /var/lib/pgsql/data/pg_hba.conf
# service is disabled by default
systemctl enable postgresql.service
# service is not started by default
service postgresql start
# need to manually create user for semaphore? setup doesn't work with root, doesn't work with default 'postgres' user
sudo -u postgres psql -c "create user semaphore with password 'semaphore';"
# no idea what permissions semaphore needs as it doesn't seem to be documented anywhere easily findable, so just get all permissions out of the way granting everything
sudo -u postgres psql -c "alter user semaphore with superuser;"
```
and still failing to setup....
```
2023-10-18 11:17:55 postgres@ansible:~$ semaphore setup

Hello! You will now be guided through a setup to:

1. Set up configuration for a MySQL/MariaDB database
2. Set up a path for your playbooks (auto-created)
3. Run database Migrations
4. Set up initial semaphore user & password

What database to use:
   1 - MySQL
   2 - BoltDB
   3 - PostgreSQL
 (default 1): 3

db Hostname (default 127.0.0.1:5432): 

db User (default root): semaphore                

db Password: semaphore

db Name (default semaphore): 

Playbook path (default /tmp/semaphore): 

Public URL (optional, example: https://example.com/semaphore): 

Enable email alerts? (yes/no) (default no): 

Enable telegram alerts? (yes/no) (default no): 

Enable slack alerts? (yes/no) (default no): 

Enable LDAP authentication? (yes/no) (default no): 

Config output directory (default /var/lib/pgsql): 

Running: mkdir -p /var/lib/pgsql..
Configuration written to /var/lib/pgsql/config.json..
 Pinging db..
WARN[0019] pq: Ident authentication failed for user "semaphore" 
panic: pq: Ident authentication failed for user "semaphore"
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa831b7]

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Close(0x22fbc60?, {0x278d998?, 0xc000148f30?})
        /home/runner/work/semaphore/semaphore/db/sql/SqlDb.go:263 +0x17
panic({0xb4c9a0, 0xc000232000})
        /opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:884 +0x212
github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Connect(0xc000012720, {0xc000012020?, 0xc000149988?})
        /home/runner/work/semaphore/semaphore/db/sql/SqlDb.go:290 +0xb05
github.com/ansible-semaphore/semaphore/cli/cmd.doSetup()
        /home/runner/work/semaphore/semaphore/cli/cmd/setup.go:41 +0x17f
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func5(0x2751400?, {0xbf6e8e?, 0x0?, 0x0?})
        /home/runner/work/semaphore/semaphore/cli/cmd/setup.go:23 +0x17
github.com/spf13/cobra.(*Command).execute(0x2751400, {0x278d998, 0x0, 0x0})
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x274fb00)
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
        /home/runner/work/semaphore/semaphore/cli/cmd/root.go:37 +0x5b
main.main()
        /home/runner/work/semaphore/semaphore/cli/main.go:8 +0x17
2023-10-18 11:19:54 postgres@ansible:~$ psql --user semaphore --password semaphore
Password: 
psql (13.11)
Type "help" for help.

semaphore=# \q
2023-10-18 11:21:14 postgres@ansible:~$ 
```

**Comment by reukiodo** [comment]
tried again after manually creating a `semaphore` linux user:
```
2023-10-18 11:27:11 root@ansible:~# adduser semaphore
2023-10-18 11:27:28 root@ansible:~# su - semaphore
2023-10-18 11:27:33 semaphore@ansible:~$ pwd
/home/semaphore
2023-10-18 11:27:34 semaphore@ansible:~$ semaphore setup

Hello! You will now be guided through a setup to:

1. Set up configuration for a MySQL/MariaDB database
2. Set up a path for your playbooks (auto-created)
3. Run database Migrations
4. Set up initial semaphore user & password

What database to use:
   1 - MySQL
   2 - BoltDB
   3 - PostgreSQL
 (default 1): 3

db Hostname (default 127.0.0.1:5432): 

db User (default root): semaphore

db Password: semaphore

db Name (default semaphore): 

Playbook path (default /tmp/semaphore): 

Public URL (optional, example: https://example.com/semaphore): 

Enable email alerts? (yes/no) (default no): 

Enable telegram alerts? (yes/no) (default no): 

Enable slack alerts? (yes/no) (default no): 

Enable LDAP authentication? (yes/no) (default no): 

Config output directory (default /home/semaphore): 

Running: mkdir -p /home/semaphore..
Configuration written to /home/semaphore/config.json..
 Pinging db..
WARN[0008] pq: Ident authentication failed for user "semaphore" 
panic: pq: Ident authentication failed for user "semaphore"
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa831b7]

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Close(0x22fbc60?, {0x278d998?, 0xc000154f30?})
        /home/runner/work/semaphore/semaphore/db/sql/SqlDb.go:263 +0x17
panic({0xb4c9a0, 0xc0000a7e60})
        /opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:884 +0x212
github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Connect(0xc000012720, {0xc000012020?, 0xc000155988?})
        /home/runner/work/semaphore/semaphore/db/sql/SqlDb.go:290 +0xb05
github.com/ansible-semaphore/semaphore/cli/cmd.doSetup()
        /home/runner/work/semaphore/semaphore/cli/cmd/setup.go:41 +0x17f
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func5(0x2751400?, {0xbf6e8e?, 0x0?, 0x0?})
        /home/runner/work/semaphore/semaphore/cli/cmd/setup.go:23 +0x17
github.com/spf13/cobra.(*Command).execute(0x2751400, {0x278d998, 0x0, 0x0})
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x274fb00)
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
        /home/runner/work/semaphore/semaphore/cli/cmd/root.go:37 +0x5b
main.main()
        /home/runner/work/semaphore/semaphore/cli/main.go:8 +0x17
2023-10-18 11:28:22 semaphore@ansible:~$ psql --user semaphore --password semaphore
Password: 
psql (13.11)
Type "help" for help.

semaphore=# \conninfo
You are connected to database "semaphore" as user "semaphore" via socket in "/var/run/postgresql" at port "5432".
semaphore=# \q
2023-10-18 11:28:43 semaphore@ansible:~$ 
```

no change - able to manually log into the db, and `semaphore setup` still fails

**Comment by reukiodo** [comment]
more env details:
```
2023-10-18 12:02:19 root@ansible:~# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
2023-10-18 12:02:22 root@ansible:~# cat /proc/version 
Linux version 5.14.0-284.30.1.el9_2.x86_64 (mockbuild@x86-64-01.build.eng.rdu2.redhat.com) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-37.el9) #1 SMP PREEMPT_DYNAMIC Fri Aug 25 09:13:12 EDT 2023
2023-10-18 12:02:27 root@ansible:~# rpm -q semaphore
semaphore-2.9.37-1.x86_64
2023-10-18 12:02:40 root@ansible:~# 
```

**Comment by andreiwow2** [comment]
I also can't get it to work with postgresql, I get this:

```
| Pinging database on postgresql port 5432...
semaphore-1  | No additional python dependencies to install
semaphore-1  | Starting semaphore server
semaphore-1  | Loading config
semaphore-1  | Validating config
semaphore-1  | Executing migration v0.0.0 (at 2025-05-03 08:05:14.835852731 +0000 UTC)...
semaphore-1  | Creating migrations table
semaphore-1  | Rolling back v0.0.0 (time: 2025-05-03 08:05:14.837482358 +0000 UTC)...
semaphore-1  | panic: open migrations/v0.0.0.err.sql: file does not exist
```
