### ISSUE TITLE
Login stops working after a couple of hours (502 error)

### ISSUE THREAD

**Issue by christianlilja** [ansible-semaphore/semaphore#1600]
Version: Latest semaphore docker amd64 with external dedicated mysql DB.
Browser: Firefox latest and Edge latest.
Problem: At first semaphore works great but after a couple I cant login any longer. Via reverse proxy (NPM) I get an 502 error.

![image](https://github.com/ansible-semaphore/semaphore/assets/33465069/d83dcdd1-690b-4e70-976f-996ce499ca7d)

When I try to connect directly to the ip:port the page loads but nothing happens when I push login.

The only fix is to restart the semaphore container again and then everything repeats itself after a couple of hours.

Docker logs:
-----------------------------
2023-10-29T20:39:06.340737879+01:00 [mysql] 2023/10/29 19:39:06 connection.go:196: busy buffer

2023-10-29T20:39:06.340782189+01:00 time="2023-10-29T19:39:06Z" level=error msg="invalid connection"

2023-10-29T20:39:06.340789485+01:00 [mysql] 2023/10/29 19:39:06 connection.go:196: busy buffer

2023-10-29T20:39:06.341193512+01:00 2023/10/29 19:39:06 http: panic serving 192.168.2.109:59674: invalid connection

2023-10-29T20:39:06.341208267+01:00 goroutine 1899 [running]:

2023-10-29T20:39:06.341211246+01:00 net/http.(*conn).serve.func1()

2023-10-29T20:39:06.341213713+01:00 	/usr/local/go/src/net/http/server.go:1850 +0xbf

2023-10-29T20:39:06.341216512+01:00 panic({0xb1e880, 0xc000170c30})

2023-10-29T20:39:06.341218977+01:00 	/usr/local/go/src/runtime/panic.go:890 +0x262

2023-10-29T20:39:06.341221495+01:00 github.com/ansible-semaphore/semaphore/api.createSession({0x2300ec0, 0xc00100b260}, 0xc001172200, {0x0, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})

2023-10-29T20:39:06.341224484+01:00 	/go/src/github.com/ansible-semaphore/semaphore/api/login.go:147 +0x4a5

2023-10-29T20:39:06.341231644+01:00 github.com/ansible-semaphore/semaphore/api.login({0x2300ec0, 0xc00100b260}, 0xc001172200)

2023-10-29T20:39:06.341234157+01:00 	/go/src/github.com/ansible-semaphore/semaphore/api/login.go:290 +0x5f8

2023-10-29T20:39:06.341236482+01:00 net/http.HandlerFunc.ServeHTTP(0xb9a700?, {0x2300ec0?, 0xc00100b260?}, 0xc?)

2023-10-29T20:39:06.341238804+01:00 	/usr/local/go/src/net/http/server.go:2109 +0x2f

2023-10-29T20:39:06.341241321+01:00 github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1({0x2300ec0, 0xc00100b260}, 0xc?)

2023-10-29T20:39:06.341243659+01:00 	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:37 +0xf4

2023-10-29T20:39:06.341245815+01:00 net/http.HandlerFunc.ServeHTTP(0xc00279e9f0?, {0x2300ec0?, 0xc00100b260?}, 0x769958?)

2023-10-29T20:39:06.341248204+01:00 	/usr/local/go/src/net/http/server.go:2109 +0x2f

2023-10-29T20:39:06.341250607+01:00 github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1.1()

2023-10-29T20:39:06.341252885+01:00 	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:28 +0x2e

2023-10-29T20:39:06.341255682+01:00 github.com/ansible-semaphore/semaphore/db.StoreSession({0x230b5c8, 0xc000012708}, {0xc00279e9f0, 0xc}, 0xc0000676c8)

2023-10-29T20:39:06.341258031+01:00 	/go/src/github.com/ansible-semaphore/semaphore/db/Store.go:354 +0x68

2023-10-29T20:39:06.341260798+01:00 github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x2300ec0, 0xc00100b260}, 0xc001172200)

2023-10-29T20:39:06.341263382+01:00 	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:27 +0xf2

2023-10-29T20:39:06.341266137+01:00 net/http.HandlerFunc.ServeHTTP(0xc001172200?, {0x2300ec0?, 0xc00100b260?}, 0xb97100?)

2023-10-29T20:39:06.341268555+01:00 	/usr/local/go/src/net/http/server.go:2109 +0x2f

2023-10-29T20:39:06.341271020+01:00 github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x2300ec0, 0xc00100b260}, 0xc0000677a8?)

2023-10-29T20:39:06.341273982+01:00 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:74 +0x124

2023-10-29T20:39:06.341276328+01:00 net/http.HandlerFunc.ServeHTTP(0x7f5a043b0680?, {0x2300ec0?, 0xc00100b260?}, 0x100?)

2023-10-29T20:39:06.341279057+01:00 	/usr/local/go/src/net/http/server.go:2109 +0x2f

2023-10-29T20:39:06.341282783+01:00 github.com/gorilla/mux.CORSMethodMiddleware.func1.1({0x2300ec0, 0xc00100b260}, 0xc002732660?)

**Comment by christianlilja** [comment]
Solved by switching to Bolt.
