### ISSUE TITLE
Problem: DNS traffic times out over Tailscale

### ISSUE THREAD

**Issue by lgrn** [ansible-semaphore/semaphore#2018]
### Issue

I've installed Semaphore on Alpine in an LXC container, when starting the service I see this:
```
(...)
Interface tailscale0
Port 3000
Server is running
time="2024-05-13T08:07:15Z" level=panic msg="listen tcp: lookup tailscale0 on 100.100.100.100:53: read udp 100.64.0.20:43359->100.100.100.100:53: i/o timeout"
panic: (*logrus.Entry) 0xc00049a1c0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00049a150, 0x0, {0xc000074230, 0x70})
        /home/runner/work/semaphore/semaphore/vendor/github.com/sirupsen/logrus/entry.go:260 +0x491
github.com/sirupsen/logrus.(*Entry).Log(0xc00049a150, 0x0, {0xc000487b70?, 0xe8?, 0xc000444ff0?})
        /home/runner/work/semaphore/semaphore/vendor/github.com/sirupsen/logrus/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Logger).Log(0x1cd3580, 0x0, {0xc000487b70, 0x1, 0x1})
        /home/runner/work/semaphore/semaphore/vendor/github.com/sirupsen/logrus/logger.go:204 +0x58
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /home/runner/work/semaphore/semaphore/vendor/github.com/sirupsen/logrus/logger.go:253
github.com/sirupsen/logrus.Panic(...)
        /home/runner/work/semaphore/semaphore/vendor/github.com/sirupsen/logrus/exported.go:129
github.com/ansible-semaphore/semaphore/cli/cmd.runService()
        /home/runner/work/semaphore/semaphore/cli/cmd/root.go:94 +0x92e
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func6(0xc000184f00?, {0xc42d74?, 0x4?, 0xc42d78?})
        /home/runner/work/semaphore/semaphore/cli/cmd/server.go:18 +0xf
github.com/spf13/cobra.(*Command).execute(0x1cd5e80, {0xc00003f5b0, 0x1, 0x1})
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x1cd5300)
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:1039
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
        /home/runner/work/semaphore/semaphore/cli/cmd/root.go:37 +0x54
main.main()
        /home/runner/work/semaphore/semaphore/cli/main.go:8 +0xf
Loading config
Validating config
(...)
```

The obvious theory would be that the DNS is actually broken, but it's not:
```
# cat /etc/resolv.conf
# resolv.conf(5) file generated by tailscale
# For more info, see https://tailscale.com/s/resolvconf-overwrite
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search foo.vpn
```
```
# dig @100.100.100.100 bar.foo.vpn

; <<>> DiG 9.18.24 <<>> @100.100.100.100 bar.foovpn
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14944
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bar.foo.vpn.            IN      A

;; ANSWER SECTION:
bar.foo.vpn.     600     IN      A       100.64.0.10

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100) (UDP)
;; WHEN: Mon May 13 08:11:32 UTC 2024
;; MSG SIZE  rcvd: 70
```
```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN qlen 500
    link/[65534]
    inet 100.64.0.20/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fe80::a4d6:f2df:dbf7:4185/64 scope link flags 800
       valid_lft forever preferred_lft forever
7: eth0@tailscale0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 00:16:3e:30:63:65 brd ff:ff:ff:ff:ff:ff
    inet 192.168.17.147/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe30:6365/64 scope link
       valid_lft forever preferred_lft forever
```
```
# cat /etc/semaphore/config.json
{
  "bolt": {
    "host": "/var/lib/semaphore.bolt"
  },
  "dialect": "bolt",
  "port": "3000",
  "interface": "tailscale0",
(...)
```
I've also tried `eth0@tailscale0` as the interface, but this doesn't help (`no such host`).

### Impact

Configuration

### Installation method

Binary

### Semaphore Version

v2.9.75

**Comment by tboerger** [comment]
The name of the option is missleading... It's not the network interface, it's the ip address you want to bind to.

**Comment by lgrn** [comment]
"misleading" is putting it mildly, and how the option is [described in the documentation](https://docs.semui.co/administration-guide/configuration#configuration-options) doesn't help:

> `interface`
> Useful if your server has multiple network interfaces

Anyway, I changed it to the IP instead of the interface and it seems to work:
```
tcp        0      0 100.64.0.20:3000        0.0.0.0:*               LISTEN      655/semaphore
```
