### ISSUE TITLE
Page "Task Templates" takes forever to load.

### ISSUE THREAD

**Issue by Banane6077** [ansible-semaphore/semaphore#2136]
### Issue

Hello fellow people,

i mastered to install and setup Semaphore on one of my Servers.

The Tasks are running fine but if i want to navigate to the Templates it takes soo long until it finally shows all my Tasks.

I already upgraded it to 2.9.113-beta-cf11555-1717159188!
Every othe Site in the UI works fine and fast!

It gets to the point to be really annoying if i want to setup a new Task.
Is there a fix to that?

I installed semaphore over the normal package manager.
Where are the logs located?
I can't find it anywhere.

Thanks for your help!

### Impact

Web-Frontend (what users interact with)

### Installation method

Package

### Database

Postgres

### Browser

Chrome

### Semaphore Version

2.9.113-beta

### Ansible Version

```bash
Collection                               Version
---------------------------------------- -------
amazon.aws                               7.2.0
ansible.netcommon                        5.3.0
ansible.posix                            1.5.4
ansible.utils                            2.12.0
ansible.windows                          2.2.0
arista.eos                               6.2.2
awx.awx                                  23.6.0
azure.azcollection                       1.19.0
check_point.mgmt                         5.2.2
chocolatey.chocolatey                    1.5.1
cisco.aci                                2.8.0
cisco.asa                                4.0.3
cisco.dnac                               6.10.2
cisco.intersight                         2.0.7
cisco.ios                                5.3.0
cisco.iosxr                              6.1.1
cisco.ise                                2.7.0
cisco.meraki                             2.17.2
cisco.mso                                2.5.0
cisco.nxos                               5.3.0
cisco.ucs                                1.10.0
cloud.common                             2.1.4
cloudscale_ch.cloud                      2.3.1
community.aws                            7.1.0
community.azure                          2.0.0
community.ciscosmb                       1.0.7
community.crypto                         2.17.1
community.digitalocean                   1.26.0
community.dns                            2.8.0
community.docker                         3.7.0
community.general                        8.3.0
community.grafana                        1.7.0
community.hashi_vault                    6.1.0
community.hrobot                         1.9.0
community.library_inventory_filtering_v1 1.0.0
community.libvirt                        1.3.0
community.mongodb                        1.6.3
community.mysql                          3.8.0
community.network                        5.0.2
community.okd                            2.3.0
community.postgresql                     3.3.0
community.proxysql                       1.5.1
community.rabbitmq                       1.2.3
community.routeros                       2.12.0
community.sap                            2.0.0
community.sap_libs                       1.4.2
community.sops                           1.6.7
community.vmware                         4.1.0
community.windows                        2.1.0
community.zabbix                         2.3.1
containers.podman                        1.11.0
cyberark.conjur                          1.2.2
cyberark.pas                             1.0.25
dellemc.enterprise_sonic                 2.4.0
dellemc.openmanage                       8.7.0
dellemc.powerflex                        2.1.0
dellemc.unity                            1.7.1
f5networks.f5_modules                    1.27.1
fortinet.fortimanager                    2.3.1
fortinet.fortios                         2.3.4
frr.frr                                  2.0.2
gluster.gluster                          1.0.2
google.cloud                             1.3.0
grafana.grafana                          2.2.4
hetzner.hcloud                           2.4.1
hpe.nimble                               1.1.4
ibm.qradar                               2.1.0
ibm.spectrum_virtualize                  2.0.0
ibm.storage_virtualize                   2.2.0
infinidat.infinibox                      1.3.12
infoblox.nios_modules                    1.6.1
inspur.ispim                             2.2.0
inspur.sm                                2.3.0
junipernetworks.junos                    5.3.1
kubernetes.core                          2.4.0
lowlydba.sqlserver                       2.2.2
microsoft.ad                             1.4.1
netapp.aws                               21.7.1
netapp.azure                             21.10.1
netapp.cloudmanager                      21.22.1
netapp.elementsw                         21.7.0
netapp.ontap                             22.9.0
netapp.storagegrid                       21.11.1
netapp.um_info                           21.8.1
netapp_eseries.santricity                1.4.0
netbox.netbox                            3.16.0
ngine_io.cloudstack                      2.3.0
ngine_io.exoscale                        1.1.0
openstack.cloud                          2.2.0
openvswitch.openvswitch                  2.1.1
ovirt.ovirt                              3.2.0
purestorage.flasharray                   1.26.0
purestorage.flashblade                   1.15.0
purestorage.fusion                       1.6.0
sensu.sensu_go                           1.14.0
splunk.es                                2.1.2
t_systems_mms.icinga_director            2.0.1
telekom_mms.icinga_director              1.35.0
theforeman.foreman                       3.15.0
vmware.vmware_rest                       2.3.1
vultr.cloud                              1.12.1
vyos.vyos                                4.1.0
wti.remote                               1.0.5
```

### Logs & errors

4Templates.vue:396 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'find')
    at a.onWebsocketDataReceived (Templates.vue:396:1)
    at Templates.vue:280:1
    at Listenable.js:24:7
    at Array.forEach (<anonymous>)
    at Q.callListeners (Listenable.js:22:50)
    at ws.onmessage (Socket.js:24:12)
onWebsocketDataReceived @ Templates.vue:396
(anonymous) @ Templates.vue:280
(anonymous) @ Listenable.js:24
callListeners @ Listenable.js:22
ws.onmessage @ Socket.js:24
2templates:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
10Templates.vue:396 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'find')
    at a.onWebsocketDataReceived (Templates.vue:396:1)
    at Templates.vue:280:1
    at Listenable.js:24:7
    at Array.forEach (<anonymous>)
    at Q.callListeners (Listenable.js:22:50)
    at ws.onmessage (Socket.js:24:12)

### Manual installation - system information

Linux 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fiftin** [comment]
It is looks like Frontend bug.

**Comment by fiftin** [comment]
Aaa, do you use nginx as reverse proxy for semaphore?

**Comment by Banane6077** [comment]
> Aaa, do you use nginx as reverse proxy for semaphore?

Nope, only in my local network. No need for a reverse proxy

**Comment by Banane6077** [comment]
> It is looks like Frontend bug.

Funny thing, if i switch to a empty project it works fine..

**Comment by fiftin** [comment]
Hi @Banane6077 what database do you use?

**Comment by fiftin** [comment]
Hi @Banane6077 could you open DevTool of Chrome? Will you see some errors in the console?
