### ISSUE TITLE
Problem: Starting a task always returns 502

### ISSUE THREAD

**Issue by dominikspiertz** [ansible-semaphore/semaphore#2485]
### Issue

Since last week neither my scheduled nor manual task execution can be started. I immediately get a 502. By digging into the problem, I tried to execute the http request to the resource of `https://mydomain.tld/api/project/1/tasks` manually with the payload from the UI by using postman. Same issue occurs, when I do it inside the container by using a curl that targets `http://localhost:3000/api/project/1/tasks`. Always a 502 that fails immediately.

### Impact

Web-Backend (APIs), Service (scheduled tasks, alerts), Ansible (task execution)

### Installation method

Docker

### Database

Postgres

### Browser

Chrome, Safari

### Semaphore Version

v2.10.32

### Logs & errors

![Screenshot 2024-10-23 at 15 43 59](https://github.com/user-attachments/assets/42177bdd-2bb7-46c7-ac2d-36fc54d87806)

### Manual installation - system information

Traefik v3.1.6

**Comment by fiftin** [comment]
Hi @dominikspiertz

Any records in Semaphore's log? It looks like Semaphore is crashing or freezing.

**Comment by dominikspiertz** [comment]
Hey @fiftin thanks for your support. There is indeed a stack trace thrown in the logs. It seems there is an issue with some kind of base64 data. I did not change my setup or my keys / secrets during the last weeks. Maybe an underlying issue with a golang update or backend code?

```
2024/10/26 19:46:11 http: panic serving 172.20.0.6:57578: illegal base64 data at input byte 13
goroutine 1944 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1898 +0xb0
panic({0x700760?, 0x1946188?})
	/usr/local/go/src/runtime/panic.go:770 +0x124
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).prepareError(0x4000106608, {0x14c08a0, 0x1946188}, {0x80a9e1, 0x1d})
	/go/src/semaphore/services/tasks/TaskRunner.go:200 +0xc0
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskRunner).populateDetails(0x4000106608)
	/go/src/semaphore/services/tasks/TaskRunner.go:266 +0x560
github.com/ansible-semaphore/semaphore/services/tasks.(*TaskPool).AddTask(_, {0x0, 0x1, 0x1, {0x7f54e6, 0x7}, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...)
	/go/src/semaphore/services/tasks/TaskPool.go:365 +0x3e8
github.com/ansible-semaphore/semaphore/api/projects.AddTask({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/api/projects/tasks.go:26 +0x188
net/http.HandlerFunc.ServeHTTP(0x40001c53e8?, {0x14c5560?, 0x4000100b60?}, 0x40001d7320?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/api.Route.GetMustCanMiddleware.func2.1({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/api/projects/project.go:59 +0x144
net/http.HandlerFunc.ServeHTTP(0x40001d70e0?, {0x14c5560?, 0x4000100b60?}, 0x7b3ea0?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/api/projects/project.go:43 +0x368
net/http.HandlerFunc.ServeHTTP(0x14c5560?, {0x14c5560?, 0x4000100b60?}, 0x7100000000000000?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/api.authentication.func1({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/api/auth.go:102 +0x58
net/http.HandlerFunc.ServeHTTP(0x78f5c0?, {0x14c5560?, 0x4000100b60?}, 0xc?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/api/router.go:45 +0xf0
net/http.HandlerFunc.ServeHTTP(0x0?, {0x14c5560?, 0x4000100b60?}, 0x5cf084?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1.1()
	/go/src/semaphore/api/router.go:36 +0x34
github.com/ansible-semaphore/semaphore/db.StoreSession({0x14d4880, 0x4000064730}, {0x400071be30, 0xc}, 0x4000665780)
	/go/src/semaphore/db/Store.go:463 +0x60
github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/api/router.go:35 +0x10c
net/http.HandlerFunc.ServeHTTP(0x40001d70e0?, {0x14c5560?, 0x4000100b60?}, 0x79aa80?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/cli/cmd/root.go:93 +0xe4
net/http.HandlerFunc.ServeHTTP(0x0?, {0x14c5560?, 0x4000100b60?}, 0x54efe0?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/api.Route.CORSMethodMiddleware.func1.1({0x14c5560, 0x4000100b60}, 0x40001d70e0)
	/go/src/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x7c
net/http.HandlerFunc.ServeHTTP(0x40001d6fc0?, {0x14c5560?, 0x4000100b60?}, 0x25210?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x40002acd80, {0x14c5560, 0x4000100b60}, 0x40001d6d80)
	/go/src/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x194
github.com/ansible-semaphore/semaphore/cli/cmd.runService.ProxyHeaders.func2({0x14c5560, 0x4000100b60}, 0x40001d6d80)
	/go/src/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x130
net/http.HandlerFunc.ServeHTTP(0x40003ed4d5?, {0x14c5560?, 0x4000100b60?}, 0x7f52649a78?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
github.com/ansible-semaphore/semaphore/cli/cmd.runService.cropTrailingSlashMiddleware.func3({0x14c5560, 0x4000100b60}, 0x40001d6d80)
	/go/src/semaphore/cli/cmd/server.go:27 +0xc4
net/http.HandlerFunc.ServeHTTP(0x10?, {0x14c5560?, 0x4000100b60?}, 0x4000100b60?)
	/usr/local/go/src/net/http/server.go:2166 +0x38
net/http.serverHandler.ServeHTTP({0x14c2fe8?}, {0x14c5560?, 0x4000100b60?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3137 +0xbc
net/http.(*conn).serve(0x40002bc090, {0x14c7428, 0x40001ca0c0})
	/usr/local/go/src/net/http/server.go:2039 +0x508
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3285 +0x3f0
```

**Comment by fiftin** [comment]
Hi @dominikspiertz are you use Runners?

**Comment by fiftin** [comment]
Which version of Semaphore are you used before? 

Looks like it is access key encryption issue.

Do you have access to the database which used by Semaphore? Please check table `access_key` column `secret`. It must be bas64.

**Comment by fiftin** [comment]
Looks like it is access key encryption issue.

**Comment by dominikspiertz** [comment]
I frequently update semaphore. I used the following versions during the last two weeks:
- v2.10.22
- v2.10.27
- v2.10.30
- v2.10.32

Yesterday I updated to v2.10.33

I have access to the database and checked the secret column. I currently have two secrets. One SSH key and another one is a password for the vault in ansible. The vault password is for sure bas64 since it ends in two padding blocks (`==`). The SSH Key is very long but it seems also to be valid as it only has numeric values and characters. Only special characters are `/` and `+`
