### ISSUE TITLE
known_hosts IOError when executed on Semaphore but succeed with ansible-playbook from CLI

### ISSUE THREAD

**Issue by kumaip** [ansible-semaphore/semaphore#272]
Hello: 

When executing the playbook from within Semaphore an IOError exception is thrown.
When executing the playbook from the CLI it runs successfully

COMPONENT NAME
ios_config

ANSIBLE VERSION
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

LOGS

```
An exception occurred during task execution. The full traceback is:
16:16:26: Traceback (most recent call last):
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_module_ios_config.py", line 333, in <module>
16:16:26:     main()
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_module_ios_config.py", line 322, in main
16:16:26:     run(module, result)
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_module_ios_config.py", line 241, in run
16:16:26:     config = get_config(module, result)
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_module_ios_config.py", line 221, in get_config
16:16:26:     contents = module.config.get_config(include_defaults=defaults)
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_modlib.zip/ansible/module_utils/network.py", line 126, in config
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_modlib.zip/ansible/module_utils/network.py", line 148, in connect
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_modlib.zip/ansible/module_utils/ios.py", line 180, in connect
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_modlib.zip/ansible/module_utils/shell.py", line 226, in connect
16:16:26:   File "/tmp/ansible_QqRJsL/ansible_modlib.zip/ansible/module_utils/shell.py", line 96, in open
16:16:26:   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 288, in connect
16:16:26:     server_key)
16:16:26:   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 556, in missing_host_key
16:16:26:     client.save_host_keys(client._host_keys_filename)
16:16:26:   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 137, in save_host_keys
16:16:26:     self.load_host_keys(self._host_keys_filename)
16:16:26:   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 121, in load_host_keys
16:16:26:     self._host_keys.load(filename)
16:16:26:   File "/usr/lib/python2.7/dist-packages/paramiko/hostkeys.py", line 94, in load
16:16:26:     with open(filename, 'r') as f:
16:16:26: IOError: [Errno 2] No such file or directory: '/etc/ansible/.ssh/known_hosts'
```

**Comment by matejkramny** [comment]
As ansible suggests, your error is:

```
[Errno 2] No such file or directory: '/etc/ansible/.ssh/known_hosts'
```

SSH seems to be having trouble creating the `.ssh` directory, either it doesn't have permissions to do so or `/etc/ansible` doesn't exist..

Try this: `mkdir -p /etc/ansible/.ssh`

**Comment by kumaip** [comment]
I've already made the directory, but still the same error, nothing changed. That's why I posted for help here

**Comment by strangeman** [comment]
Does have semaphore user read permissions for the /etc/ansible/.ssh/known_hosts file?

**Comment by kumaip** [comment]
Ah thanks, it works, have a good day
