### ISSUE TITLE
Alerts not working

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#329]
After merge and release, alerts was broken:

```
Stopped running tasks
panic: template: mail body template:3:8: executing "mail body template" at <.TaskId>: can't evaluate field TaskId in type tasks.Alert

goroutine 564 [running]:
github.com/ansible-semaphore/semaphore/api/tasks.(*task).sendMailAlert(0xc42001e300)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/alert.go:46 +0x821
github.com/ansible-semaphore/semaphore/api/tasks.(*task).fail(0xc42001e300)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:34 +0x5a
github.com/ansible-semaphore/semaphore/api/tasks.(*task).run(0xc42001e300)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:120 +0x692
created by github.com/ansible-semaphore/semaphore/api/tasks.(*taskPool).run
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/pool.go:32 +0x274
(error exit: exit status 2)
```

**Comment by strangeman** [comment]
Closed by https://github.com/ansible-semaphore/semaphore/pull/330
