### ISSUE TITLE
Failed default login

### ISSUE THREAD

**Issue by mickengland** [ansible-semaphore/semaphore#33]
Hi,

I have just installed Semaphore under vagrant following the readme instructions but I am unable to login with the default credentials. The Semaphore login page comes up fine at localhost:3000 but then I get this:

0 Request Failed. Try again later.

Any advice on how to correct this?

**Comment by matejkramny** [comment]
Do you know how to use a mongo database?

The system should automatically try and setup an initial user, if for some reason it didn't, the record wouldn't be in the `users` collection.

What's your setup?

**Comment by eperry** [comment]
I have come up with this same problem (or at least simular)

I am running on RHEL7  ,  I have tried the instructions on the front page and tried the playbook.yaml. With changes for rhel. Both processes give me this exception when I try to login.

Mongo and redis are both system installs ( yum install redis mongodb-server ) and they are up an running.

I show semaphore connection to mongo 
`[root@hd1melk10lx semaphore]# nodemon bin/semaphore
5 Sep 19:00:06 - [nodemon] v1.4.1
5 Sep 19:00:06 - [nodemon] to restart at any time, enter `rs`
5 Sep 19:00:06 - [nodemon] watching: *.*
5 Sep 19:00:06 - [nodemon] starting `node bin/semaphore bin/semaphore.js`
app.js:110 Semaphore listening on port 80
app.js:47 Mongodb connection established
../node_modules/bugsnag/lib/logger.js:29 Bugsnag:  TypeError: Cannot set property 'user' of undefined
    at /home/semaphore/node_modules/passport.socketio/node_modules/passport/lib/http/request.js:50:35
    at pass (/home/semaphore/node_modules/passport/lib/authenticator.js:267:43)
    at serialized (/home/semaphore/node_modules/passport/lib/authenticator.js:276:7)
    at passport.deserializeUser.models.User.findOne._id (/home/semaphore/lib/auth.js:6:2)
    at pass (/home/semaphore/node_modules/passport/lib/authenticator.js:284:9)
    at Authenticator.serializeUser (/home/semaphore/node_modules/passport/lib/authenticator.js:289:5)
    at IncomingMessage.req.login.req.logIn (/home/semaphore/node_modules/passport.socketio/node_modules/passport/lib/http/request.js:48:29)
    at authCallback (/home/semaphore/lib/routes/auth.js:84:6)
    at /home/semaphore/lib/routes/auth.js:70:4
    at /home/semaphore/lib/models/User.js:30:3
5 Sep 19:00:15 - [nodemon] app crashed - waiting for file changes before starting...
`

**Comment by mickengland** [comment]
I'm not that familiar with mongo but I do see this in the semaphore logs which would suggest mongo is fine. If I do a find on the samphore.users I don't see that record.

> coll = db.users
semaphore.users
> coll.find) { name: "*" } );
Sun Sep  6 18:22:07.622 SyntaxError: Unexpected token )
> coll.find()
{ "password" : "$2a$10$yfhDNI8WLIJdYMVhC7YB5.pGPZR8YgZPEmKGy0sQZsDoIZSxfLs5C", "email" : "admin@semaphore.local", "username" : "semaphore", "name" : "Administrator", "_id" : ObjectId("55eb2d96dcb7786931180cde"), "created" : ISODate("2015-09-05T17:59:50.002Z"), "__v" : 0 }

In the semaphore logs I see this:

2015-09-06_18:16:39.41108 ^[[90m../node_modules/bugsnag/lib/logger.js:29^[[39m Bugsnag:  TypeError: Cannot set property 'user' of undefined
2015-09-06_18:16:39.41111     at /opt/semaphore/node_modules/passport.socketio/node_modules/passport/lib/http/request.js:50:35
2015-09-06_18:16:39.41112     at pass (/opt/semaphore/node_modules/passport/lib/authenticator.js:267:43)
2015-09-06_18:16:39.41113     at serialized (/opt/semaphore/node_modules/passport/lib/authenticator.js:276:7)
2015-09-06_18:16:39.41113     at passport.deserializeUser.models.User.findOne._id (/opt/semaphore/lib/auth.js:6:2)
2015-09-06_18:16:39.41114     at pass (/opt/semaphore/node_modules/passport/lib/authenticator.js:284:9)
2015-09-06_18:16:39.41114     at Authenticator.serializeUser (/opt/semaphore/node_modules/passport/lib/authenticator.js:289:5)
2015-09-06_18:16:39.41115     at IncomingMessage.req.login.req.logIn (/opt/semaphore/node_modules/passport.socketio/node_modules/passport/lib/http/request.js:48:29)
2015-09-06_18:16:39.41116     at authCallback (/opt/semaphore/lib/routes/auth.js:84:6)
2015-09-06_18:16:39.41116     at /opt/semaphore/lib/routes/auth.js:70:4
2015-09-06_18:16:39.41117     at /opt/semaphore/lib/models/User.js:30:3
2015-09-06_18:16:40.49389 ^[[90mapp.js:110^[[39m Semaphore listening on port 3000
2015-09-06_18:16:40.52483 ^[[90mapp.js:47^[[39m Mongodb connection established
2015-09-06_18:23:44.98307 ^[[0mPOST /auth/password ^[[33m400 ^[[0m30.995 ms - 42^[[0m
~        
I am running in Vagrant as described in the READ.me. It looks like the credentials are not getting created.

**Comment by matejkramny** [comment]
Ok you both have the same issue.

I figure the passport plugin has an updated api, and unfortunately, the package.json tells NPM to install the latest version..

The docker image has locked down dependencies (done at install time) which work. I won't post it into `master` as it would trigger a build and cause the same issues potentially. [Gist here](https://gist.github.com/matejkramny/04fd6ebcccc7b520e792)

If you cd into the semaphore directory, then run:
- `curl https://gist.githubusercontent.com/matejkramny/04fd6ebcccc7b520e792/raw/01d2886d4a92e212579c6ed0fca57c8da466d7d2/semaphore-shrinkwrap.json > npm-shrinkwrap.json`
- `rm -rf node_modules`
- `npm install`

Let me know how you get on.
