### ISSUE TITLE
create new template error

### ISSUE THREAD

**Issue by sungy2014** [ansible-semaphore/semaphore#334]
Error 1452: Cannot add or update a child row: a foreign key constraint fails (`semaphore`.`project__template`, CONSTRAINT `project__template_ibfk_4` FOREIGN KEY (`repository_id`) REFERENCES `project__repository` (`id`))

**Comment by sungy2014** [comment]
http: panic serving 192.168.80.1:63214: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`semaphore`.`project__template`, CONSTRAINT `project__template_ibfk_4` FOREIGN KEY (`repository_id`) REFERENCES `project__repository` (`id`))
goroutine 852 [running]:
net/http.(*conn).serve.func1(0xc4202e0dc0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x9a4880, 0xc4202b8dc0)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/ansible-semaphore/semaphore/api/projects.AddTemplate(0xce7e60, 0xc420630d40, 0xc420374500)
	/Users/m/p/go/src/github.com/ansible-semaphore/semaphore/api/projects/templates.go:102 +0x3fd
github.com/castawaylabs/mulekick.Router.Handle.func1(0xce8460, 0xc4204781c0, 0xc420374500)
	/Users/m/p/go/src/github.com/castawaylabs/mulekick/router.go:69 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc42030cd20, 0xce8460, 0xc4204781c0, 0xc420374500)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201e1900, 0xce8460, 0xc4204781c0, 0xc420374500)
	/Users/m/p/go/src/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/gorilla/handlers.ProxyHeaders.func1(0xce8460, 0xc4204781c0, 0xc4202de000)
	/Users/m/p/go/src/github.com/gorilla/handlers/proxy_headers.go:59 +0x117
net/http.HandlerFunc.ServeHTTP(0xc42030f600, 0xce8460, 0xc4204781c0, 0xc4202de000)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xe76a20, 0xce8460, 0xc4204781c0, 0xc4202de000)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420336000, 0xce8460, 0xc4204781c0, 0xc4202de000)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4202e0dc0, 0xce8c20, 0xc420572540)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce

**Comment by sungy2014** [comment]
I havent create repostitory first
