### ISSUE TITLE
How to build semaphore in centos7

### ISSUE THREAD

**Issue by jffree** [ansible-semaphore/semaphore#409]
I want to build semaphore in centos7, but there are a lot of error. How can I fix these?

`module.js:471
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/semaphore/public/bundler.js:2:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

**Comment by jffree** [comment]
npm install async.

`
Error: ENOENT: no such file or directory, open './vendor/angular.min.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at bundle.forEach.file (/opt/semaphore/public/bundler.js:23:20)
    at Array.forEach (native)
    at Object.<anonymous> (/opt/semaphore/public/bundler.js:9:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)`

**Comment by idkCpp** [comment]
@jffree Would you mind sharing how you fixed this?
