### ISSUE TITLE
When I build semaphore , which nodejs version should I choose?

### ISSUE THREAD

**Issue by jffree** [ansible-semaphore/semaphore#423]
Can semaphore be build in centos6?
I got this problem:

```
/home/mock/rpmbuild/BUILD/semaphore-2.4.1/src/github.com/ansible-semaphore/semaphore/public/bundler.js:9
bundle.forEach(file => {
                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

centos6  :  nodejs-0.10.48-3

**Comment by strangeman** [comment]
Node.js LTS (6.x) will be enough. You can install it from the official site: https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

**Comment by Echobob** [comment]
Closing due to inactivity. Let up know if you're still having trouble.
