### ISSUE TITLE
Deleting a running task whilst it is logging causes a panic

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#459]
Currently if you delete a running task whilst it is logging you get an issue where the log item cannot be inserted because the task id does not exist any more.
```
Failed to insert task output: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`semaphore`.`task__output`, CONSTRAINT `task__output_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`) ON DELETE CASCADE)
semaphore_dev_1  | panic: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`semaphore`.`task__output`, CONSTRAINT `task__output_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`) ON DELETE CASCADE)
semaphore_dev_1  | 
semaphore_dev_1  | goroutine 732 [running]:
semaphore_dev_1  | github.com/ansible-semaphore/semaphore/api/tasks.(*task).log.func1(0xc42020a380, 0xc42019a600, 0x3a, 0xbe99435414f98ab7, 0x1765fb470a, 0x5571db885380)
semaphore_dev_1  |      /go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:37 +0x26b
semaphore_dev_1  | created by github.com/ansible-semaphore/semaphore/api/tasks.(*task).log
semaphore_dev_1  |      /go/src/github.com/ansible-semaphore/semaphore/api/tasks/logging.go:33 +0x617
```
unfortunately this sort of exit can be quite common with long playbooks that skip a lot of tasks in a row, or log a lot very quickly and get deleted.

Either we should consider all errors of this type to be a soft fail, or attempt to recover from the panic by checking if the task id still exists in the db (thus indicating some other kind of error occurred), and if it does not continue execution of the app.

**Comment by fiftin** [comment]
Related to https://github.com/ansible-semaphore/semaphore/issues/392
