### ISSUE TITLE
Reduce when panic is called

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#462]
Currently semaphore panics a lot, which crashes the whole app. This is especially problematic in docker environments. IMO even if the db is not available (a common panic cause currently) the application itself should not crash. If within the context of a task it should halt the job, but the application itself should not exit.

**Comment by strangeman** [comment]
```
panic: Post https://api.telegram.org/botXXXXXXXX:XXXXXXXXXXXXXXXXXXX/sendMessage: dial tcp: lookup api.telegram.org on 104.238.186.189:53: read udp 192.168.0.71:47609->104.238.186.189:53: i/o timeout

goroutine 387 [running]:
github.com/ansible-semaphore/semaphore/api/tasks.(*task).sendTelegramAlert(0xc420b68000)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/alert.go:101 +0x448
github.com/ansible-semaphore/semaphore/api/tasks.(*task).fail(0xc420b68000)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:40 +0x68
github.com/ansible-semaphore/semaphore/api/tasks.(*task).prepareRun(0xc420b68000)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:111 +0x618
created by github.com/ansible-semaphore/semaphore/api/tasks.(*taskPool).run
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/pool.go:77 +0x4e1
```

Network connection troubles should be handled w/o panic and crash.

**Comment by matejkramny** [comment]
hmm agreed. Maybe we could keep the panics and implement a recover at the top of the routing stack.

Re database connection at the start, are we proposing to let it sit and wait until the db can be connected?

**Comment by fiftin** [comment]
Done
