### ISSUE TITLE
Panic when can't connect to Telegram server

### ISSUE THREAD

**Issue by strangeman** [ansible-semaphore/semaphore#500]
```
panic: Post https://api.telegram.org/botXXXXXXXX:XXXXXXXXXXXXXXXXXXX/sendMessage: dial tcp: lookup api.telegram.org on 104.238.186.189:53: read udp 192.168.0.71:47609->104.238.186.189:53: i/o timeout

goroutine 387 [running]:
github.com/ansible-semaphore/semaphore/api/tasks.(*task).sendTelegramAlert(0xc420b68000)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/alert.go:101 +0x448
github.com/ansible-semaphore/semaphore/api/tasks.(*task).fail(0xc420b68000)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:40 +0x68
github.com/ansible-semaphore/semaphore/api/tasks.(*task).prepareRun(0xc420b68000)
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:111 +0x618
created by github.com/ansible-semaphore/semaphore/api/tasks.(*taskPool).run
	/mnt/src/sources/go/src/github.com/ansible-semaphore/semaphore/api/tasks/pool.go:77 +0x4e1
```

Network connection troubles should be handled w/o panic and crash.
Related to https://github.com/ansible-semaphore/semaphore/issues/462

**Comment by twhiston** [comment]
Can we move this to a comment in #462 so we keep all the panic related pain in one place and dont forget about any of them when the work gets done?

**Comment by strangeman** [comment]
merged with https://github.com/ansible-semaphore/semaphore/issues/462
