### ISSUE TITLE
"No roles/requirements.yml file found" Even though the file exists

### ISSUE THREAD

**Issue by insanity54** [ansible-semaphore/semaphore#713]
I'm confused by the error, "No roles/requirements.yml file found. Skip galaxy install process."

 ```
7:13:21 PM Task 2147483639 added to queue
7:13:22 PM Prepare task with template: immls
7:13:22 PM access key LEO-COMPUTE installed
7:13:22 PM Updating repository https://github.com/****/****.git
7:13:23 PM From https://github.com/****/****
7:13:23 PM * branch main -> FETCH_HEAD
7:13:23 PM 7773032..90c7a60 main -> origin/main
7:13:23 PM Updating 7773032..90c7a60
7:13:23 PM Fast-forward
7:13:23 PM roles/requirements.yml | 2 +-
7:13:23 PM 1 file changed, 1 insertion(+), 1 deletion(-)
7:13:23 PM access key LEO-COMPUTE installed
7:13:23 PM installing static inventory
7:13:23 PM No roles/requirements.yml file found. Skip galaxy install process.
7:13:23 PM Listing playbook hosts failed: fork/exec /root/snap/semaphore/common/ansible_env/bin/ansible-playbook: no such file or directory 
```
The git pull result `7:13:23 PM roles/requirements.yml | 2 +-` confirms that the file exists, yet semaphore doesn't seem to be able to find that file.

I'm running semaphore v2.7.11 installed via snap

**Comment by fiftin** [comment]
I working on this bug, thank you.

**Comment by fiftin** [comment]
I found where the bug. Will be fixed asap.

**Comment by fiftin** [comment]
Hi @insanity54 

May you update semaphore via snap command:

```
 sudo snap refresh semaphore --candidate
```
?

I fixed the bug and I will be very grateful if you test new version.

**Comment by insanity54** [comment]
@fiftin I updated to semaphore v2.7.13 installed via snap.

I don't see the "No roles/requirements.yml" error anymore. I see a new error.

`10:17:19 PM Running galaxy failed: fork/exec /root/snap/semaphore/common/ansible_env/bin/ansible-galaxy: no such file or directory`

I checked. The file exists.

```
sudo ls -lash /root/snap/semaphore/common/ansible_env/bin/ansible-galaxy
[sudo] password for chris: 
8.0K -rwxr-xr-x 1 root root 6.4K Aug 29 10:42 /root/snap/semaphore/common/ansible_env/bin/ansible-galaxy
```

Seems similar to #718

**Comment by fiftin** [comment]
> 10:17:19 PM Running galaxy failed: fork/exec /root/snap/semaphore/common/ansible_env/bin/ansible-galaxy: no such file or directory

very unpleasant bug, I can't reproduce in any way...

**Comment by insanity54** [comment]
I'll try to see if I can get more data. When I switched to the semaphore installed via snap, I noticed that it had old configuration data. I will try to delete the config and fresh install the snap version.

**Comment by insanity54** [comment]
I reinstalled semaphore on snap using the following commands

```
sudo snap stop semaphore
sudo snap remove --purge semaphore
sudo rm -r /root/semaphore
```
Then I installed `sudo snap install semaphore --candidate`

Then I added a user `sudo semaphore user add --name chris --login chris@grimtech.net --email chris@grimtech.net --password ****`

That command hung, so I restarted semaphore in a different terminal.

`sudo snap restart semaphore`

The user creation command successfully completed after the restart.

I logged in to web UI, re-configured SSH key, repo, inventory, playbook, then I tried to run it and I see a new error.

```
(...)
2021-09-07T23:48:14Z semaphore.semaphored[94090]: time="2021-09-07T16:48:14-07:00" level=info msg="Task 2147483646 added to queue"
2021-09-07T23:48:17Z semaphore.semaphored[94090]: time="2021-09-07T16:48:17-07:00" level=info msg="Set resource locker with task 2147483646"
2021-09-07T23:48:17Z semaphore.semaphored[94090]: time="2021-09-07T16:48:17-07:00" level=info msg="Stopped preparing task 2147483646"
2021-09-07T23:48:17Z semaphore.semaphored[94090]: time="2021-09-07T16:48:17-07:00" level=info msg="Release resource locker with task 2147483646"
2021-09-07T23:48:17Z semaphore.semaphored[94090]: panic: invalid character '©' looking for beginning of value
2021-09-07T23:48:17Z semaphore.semaphored[94090]: goroutine 103 [running]:
2021-09-07T23:48:17Z semaphore.semaphored[94090]: github.com/ansible-semaphore/semaphore/api/tasks.(*task).prepareError(0xc000670480, 0x179efc0, 0xc000631bc0, 0xa4513e, 0x1d, 0x5, 0x1)
2021-09-07T23:48:17Z semaphore.semaphored[94090]: 	/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:273 +0xec
2021-09-07T23:48:17Z semaphore.semaphored[94090]: github.com/ansible-semaphore/semaphore/api/tasks.(*task).populateDetails(0xc000670480, 0x28, 0x0)
2021-09-07T23:48:17Z semaphore.semaphored[94090]: 	/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:312 +0x816
2021-09-07T23:48:17Z semaphore.semaphored[94090]: github.com/ansible-semaphore/semaphore/api/tasks.(*task).prepareRun(0xc000670480)
2021-09-07T23:48:17Z semaphore.semaphored[94090]: 	/go/src/github.com/ansible-semaphore/semaphore/api/tasks/runner.go:144 +0x12c
2021-09-07T23:48:17Z semaphore.semaphored[94090]: created by github.com/ansible-semaphore/semaphore/api/tasks.(*taskPool).run
2021-09-07T23:48:17Z semaphore.semaphored[94090]: 	/go/src/github.com/ansible-semaphore/semaphore/api/tasks/pool.go:149 +0x6ac
2021-09-07T23:48:17Z systemd[1]: snap.semaphore.semaphored.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2021-09-07T23:48:17Z systemd[1]: snap.semaphore.semaphored.service: Failed with result 'exit-code'.
2021-09-07T23:48:17Z systemd[1]: snap.semaphore.semaphored.service: Scheduled restart job, restart counter is at 1.
2021-09-07T23:48:17Z systemd[1]: Stopped Service for snap application semaphore.semaphored.
2021-09-07T23:48:17Z systemd[1]: Started Service for snap application semaphore.semaphored.
2021-09-07T23:48:17Z semaphore.semaphored[94539]: mkdir: cannot create directory '/root/snap/semaphore': Not a directory
(...)
```

`mkdir: cannot create directory '/root/snap/semaphore': Not a directory`

Strange. That file exists, and it is a directory.

```
sudo ls -lash /root/snap/semaphore
total 16K
4.0K drwxr-xr-x 4 root root 4.0K Sep  7 16:43 .
4.0K drwxr-xr-x 5 root root 4.0K Sep  7 16:43 ..
4.0K drwxr-xr-x 2 root root 4.0K Sep  7 16:43 86
4.0K drwxr-xr-x 4 root root 4.0K Sep  7 16:48 common
   0 lrwxrwxrwx 1 root root    2 Sep  7 16:43 current -> 86
```

Another file that exists, but semaphore is not able to tell that it exists. I'm stumped.

**Comment by fiftin** [comment]
What OS do you use?

**Comment by insanity54** [comment]
```
@CJ_Clippy:~$ uname -a
Linux LEO-COMPUTE 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
@CJ_Clippy:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Comment by fiftin** [comment]
Yahoo, bug fixed in stable version (`sudo snap install/refresh semaphore`).

**Comment by insanity54** [comment]
Thank you. I'll go ahead and close this issue now.

**Comment by morganchester** [comment]
Getting the same error in 2.8.33 and 2.8.35. 

> Jan 27 08:14:52 * systemd[1]: Started Service for snap application semaphore.semaphored.
Jan 27 08:14:53 * semaphore.semaphored[17025]: mkdir: cannot create directory '/root/snap/semaphore': Not a directory
Jan 27 08:14:53 * semaphore.semaphored[17025]:                  "host": "/root/snap/semaphore/common/database.boltdb"
Jan 27 08:14:53 * semaphore.semaphored[17025]:          "tmp_path":                         "/root/snap/semaphore/common/repositories",
Jan 27 08:14:53 * systemd[1]: snap.semaphore.semaphored.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 27 08:14:53 * systemd[1]: snap.semaphore.semaphored.service: Failed with result 'exit-code'.

CentOS Linux release 8.5.2111 
Snap 2.54.2

Suddenly failed to start.

**Comment by deba10106** [comment]
I'm facing the same issue. Any solution?

`Running playbook failed: fork/exec /root/snap/semaphore/common/ansible_env/bin/ansible-playbook: no such file or directory`

**Comment by SvartrShell** [comment]
Same issue on docker version
