### ISSUE TITLE
pq: duplicate key value violates unique constraint "user_email_key"

### ISSUE THREAD

**Issue by Vitexus** [ansible-semaphore/semaphore#776]
In case of use one of emails presented in LDAP for administrator:

```
Semaphore v2.8.2
Interface 
Port :3000
Server is running
INFO[0006] User Vitezslav Dvorak with email vitex@domain.eu authorized via LDAP correctly 
2021/10/29 11:34:18 http: panic serving 127.0.0.1:49144: pq: duplicate key value violates unique constraint "user_email_key"
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc00056a000)
        /usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x9b2620, 0xc00070a120)
        /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/ansible-semaphore/semaphore/api.login(0x17ca790, 0xc000022700, 0xc0000ab700)
        /go/src/github.com/ansible-semaphore/semaphore/api/login.go:146 +0xcb3
net/http.HandlerFunc.ServeHTTP(0x173deb0, 0x17ca790, 0xc000022700, 0xc0000ab700)
        /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1(0x17ca790, 0xc000022700, 0xc0000ab700)
        /go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0x131
net/http.HandlerFunc.ServeHTTP(0xc00053a378, 0x17ca790, 0xc000022700, 0xc0000ab700)
        /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1(0x17ca790, 0xc000022700, 0xc0000ab700)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:90 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0005ae7b0, 0x17ca790, 0xc000022700, 0xc0000ab700)
        /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0x17ca790, 0xc000022700, 0xc0000ab700)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc000513e40, 0x17ca790, 0xc000022700, 0xc0000ab700)
        /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000326000, 0x17ca790, 0xc000022700, 0xc000112100)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/gorilla/handlers.ProxyHeaders.func1(0x17ca790, 0xc000022700, 0xc000112100)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x114
net/http.HandlerFunc.ServeHTTP(0xc00053a318, 0x17ca790, 0xc000022700, 0xc000112100)
        /usr/local/go/src/net/http/server.go:2049 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1(0x17ca790, 0xc000022700, 0xc000112100)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/service.go:26 +0x97
net/http.HandlerFunc.ServeHTTP(0xc00053a330, 0x17ca790, 0xc000022700, 0xc000112100)
        /usr/local/go/src/net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc000022620, 0x17ca790, 0xc000022700, 0xc000112100)
        /usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc00056a000, 0x17cc0e0, 0xc000570000)
        /usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2993 +0x39b

```

After changing this email in database LDAP login pass well.

**Comment by fiftin** [comment]
Hi @Vitexus,

Please provide more details.

As I understood, you have account registered via Semaphore. It conflicts with LDAP account. It is right?

**Comment by fiftin** [comment]
Hm, interesting issue... Looks like a bug. Could you provide mode details?

**Comment by fiftin** [comment]
@Vitexus May be two LDAP users (with different usernames) have the same email?

Username and email must be unique in Semaphore.

**Comment by Vitexus** [comment]
I use my email address in installation script but username was "admin"

**Comment by Vitexus** [comment]
> @Vitexus May be two LDAP users (with different usernames) have the same email?
> 
> Username and email must be unique in Semaphore.

Correct. I did use my email address in installation script but username was "admin"

**Comment by mmospanenko** [comment]
Having the same issue, I don't see this email in UI, but server returns 400 with pg duplicated key user_email_key. How to debug or show all users? version Semaphore v2.9.64
