### ISSUE TITLE
Setup on Macbook with/without MAMP

### ISSUE THREAD

**Issue by slimandslam** [ansible-semaphore/semaphore#80]
Just a quick test. MacOSX 10.11.4

```
$ ./semaphore_darwin_amd64 -setup

Hello, you will now be guided through a setup to:

- Set up configuration for a MySQL/MariaDB database
- Set up redis for session storage
- Set up a path for your playbooks
- Run DB Migrations
- Set up your user and password

DB Hostname (example 127.0.0.1:3306): 127.0.0.1:8889
DB User (example root): root
DB Password: root
DB Name: semaphore
Redis Connection (example 127.0.0.1:6379):
Playbook path (will be auto-created if does not exist):
Config:
{
	"mysql": {
		"host": "127.0.0.1:8889",
		"user": "root",
		"pass": "root",
		"name": "semaphore"
	},
	"session_db": "",
	"mandrill": {
		"username": "",
		"password": ""
	},
	"port": "",
	"bugsnag_key": "",
	"tmp_path": ""
}

Is this correct? (yes/no): yes
Configuration written to /tmp/semaphore_config.json

Pinging database...
Pinging redis...
PING to redis unsuccessful
panic: dial tcp 127.0.0.1:6379: getsockopt: connection refused

goroutine 1 [running]:
panic(0x67efe0, 0xc8201f8000)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/ansible-semaphore/semaphore/database.RedisPing()
	/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/database/redis.go:25 +0x1af
main.doSetup(0x30)
	/Users/m/p/semaphore/main.go:118 +0xa51
main.main()
	/Users/m/p/semaphore/main.go:25 +0x30
2016/04/25 09:35:49 notifying bugsnag: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2016/04/25 09:35:49 bugsnag.Notify: not notifying in development
$
```

Without MAMP, I get this:

```
$ ./semaphore_darwin_amd64 -setup

Hello, you will now be guided through a setup to:

- Set up configuration for a MySQL/MariaDB database
- Set up redis for session storage
- Set up a path for your playbooks
- Run DB Migrations
- Set up your user and password

DB Hostname (example 127.0.0.1:3306):
DB User (example root): root
DB Password: root
DB Name: semaphore
Redis Connection (example 127.0.0.1:6379):
Playbook path (will be auto-created if does not exist):
Config:
{
	"mysql": {
		"host": "",
		"user": "root",
		"pass": "root",
		"name": "semaphore"
	},
	"session_db": "",
	"mandrill": {
		"username": "",
		"password": ""
	},
	"port": "",
	"bugsnag_key": "",
	"tmp_path": ""
}

Is this correct? (yes/no): yes
Configuration written to /tmp/semaphore_config.json

Pinging database...
Connection to database unsuccessful.
panic: dial tcp 127.0.0.1:3306: getsockopt: connection refused

goroutine 1 [running]:
panic(0x67efe0, 0xc820015270)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.doSetup(0x30)
	/Users/m/p/semaphore/main.go:114 +0x949
main.main()
	/Users/m/p/semaphore/main.go:25 +0x30
2016/04/25 09:41:05 notifying bugsnag: dial tcp 127.0.0.1:3306: getsockopt: connection refused
2016/04/25 09:41:05 bugsnag.Notify: not notifying in development
$
```

**Comment by matejkramny** [comment]
for the first one, you don't have `redis` running..

For the second log, mysql is not running.

It requires both mysql and redis. They can both be easily installed with homebrew

**Comment by slimandslam** [comment]
Ok. The install instructions just say:
```
Download relevant binary
./semaphore -setup
```
:-D

**Comment by matejkramny** [comment]
:)

It assumes you already have redis & mysql..

**Comment by slimandslam** [comment]
That's just one little sentence to add to the installation instructions.
 :-)

J

**Comment by matejkramny** [comment]
There will be full instructions, this is just an alpha release which was meant to be tested for auto-upgrades.

Other dependencies are:

- Ansible
- Git

**Comment by matejkramny** [comment]
See https://github.com/ansible-semaphore/semaphore/releases/tag/v2.0-beta

**Comment by slimandslam** [comment]
You could add to the instructions a sample of the questions your install
flow asks and some typical responses.

:-D

J

**Comment by matejkramny** [comment]
Beta has default responses (ie if you press nothing, it uses that value) and also auto-creates the temp path for playbooks.

**Comment by matejkramny** [comment]
Added some more instructions :P

**Comment by slimandslam** [comment]
Do I have to provide the playbook path?  Or can I provide it after
installation? (add your answer to the instructions)

J

**Comment by matejkramny** [comment]
Added

**Comment by slimandslam** [comment]
Thanks!
