### ISSUE TITLE
Login with LDAP twice results in 'duplicate key value violates unique constraint "user_username_key"'

### ISSUE THREAD

**Issue by acherla** [ansible-semaphore/semaphore#801]
1. When logging into ansible semaphore with a LDAP account it properly logs in with the correct user.
2. Log out
3. Attempt to login again and it results in a unique constraint violation for user_username_key

Conclusion:  Seems like ansible semaphore is trying to re-register the same user login through ldap every time a ldap user logs in.  Ansible semaphore should check if the user is already registered before attempting to create another entry in the database with the same user_username field value.  This does not impact the default admin account.  

This should be a critical bug as there is no way to resolve this without wiping the existing user entry in the DB.  

Ansible Semaphore Version: v2.8.22

Postgres Version: 12.08

Stack Trace:
```
2021/12/07 04:54:11 http: panic serving 192.168.7.192:22815: pq: duplicate key value violates unique constraint "user_username_key"
goroutine 77 [running]:
net/http.(*conn).serve.func1(0xc0008c9c20)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x9b7ea0, 0xc001c0c000)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/ansible-semaphore/semaphore/api.login(0x1859070, 0xc0001c3340, 0xc00054ae00)
	/go/src/github.com/ansible-semaphore/semaphore/api/login.go:146 +0xcb3
net/http.HandlerFunc.ServeHTTP(0x17cbdb0, 0x1859070, 0xc0001c3340, 0xc00054ae00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1(0x1859070, 0xc0001c3340, 0xc00054ae00)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0x131
net/http.HandlerFunc.ServeHTTP(0xc000548600, 0x1859070, 0xc0001c3340, 0xc00054ae00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1(0x1859070, 0xc0001c3340, 0xc00054ae00)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:90 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0007e9740, 0x1859070, 0xc0001c3340, 0xc00054ae00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0x1859070, 0xc0001c3340, 0xc00054ae00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc0007d0380, 0x1859070, 0xc0001c3340, 0xc00054ae00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004ba0c0, 0x1859070, 0xc0001c3340, 0xc00127c000)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/gorilla/handlers.ProxyHeaders.func1(0x1859070, 0xc0001c3340, 0xc00127c000)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x114
net/http.HandlerFunc.ServeHTTP(0xc0008d00d8, 0x1859070, 0xc0001c3340, 0xc00127c000)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1(0x1859070, 0xc0001c3340, 0xc00127c000)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/service.go:26 +0x97
net/http.HandlerFunc.ServeHTTP(0xc0008d00f0, 0x1859070, 0xc0001c3340, 0xc00127c000)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0003c8380, 0x1859070, 0xc0001c3340, 0xc00127c000)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0008c9c20, 0x185aa00, 0xc0007c36c0)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by fiftin** [comment]
Duplicate https://github.com/ansible-semaphore/semaphore/issues/776
