### ISSUE TITLE
Unknown database "semaphore" on fresh install with V2

### ISSUE THREAD

**Issue by alexrjs** [ansible-semaphore/semaphore#82]
Setup:
```
alex@myserver: docker run -d --name=redisio -p myserver:32769:6379 redis:latest
alex@myserver: docker run -d --name=mysql -p myserver:3306:3306 mariadb:latest
```
Execute:
```
alex@myserver: ./semaphore_linux_amd64 -setup

Hello, you will now be guided through a setup to:

- Set up configuration for a MySQL/MariaDB database
- Set up redis for session storage
- Set up a path for your playbooks
- Run DB Migrations
- Set up your user and password

DB Hostname (default 127.0.0.1:3306): myserver:33306
DB User (default root): 
DB Password: admin
DB Name (default semaphore): 
Redis Connection (default 127.0.0.1:6379): myserver:32769
Playbook path (will be auto-created if does not exist): 
Config:
{
	"mysql": {
		"host": "myserver:33306",
		"user": "root",
		"pass": "admin",
		"name": "semaphore"
	},
	"session_db": "myserver:32769",
	"mandrill": {
		"username": "",
		"password": ""
	},
	"port": "",
	"bugsnag_key": "",
	"tmp_path": "/tmp/semaphore"
}

Is this correct? (yes/no): yes
Running: mkdir -p /tmp/semaphore
Configuration written to /tmp/semaphore

Pinging database...
Connection to database unsuccessful.
panic: Error 1049: Unknown database 'semaphore'

goroutine 1 [running]:
panic(0xa88e60, 0xc820232220)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.doSetup(0x0)
	/Users/m/p/semaphore/main.go:128 +0xb2a
main.main()
	/Users/m/p/semaphore/main.go:27 +0x30
2016/04/29 19:19:12 notifying bugsnag: Error 1049: Unknown database 'semaphore'
homeboy@linix:~/Downloads$ 2016/04/29 19:19:12 bugsnag.Notify: not notifying in development
```

Debug:
```
alex@myserver: telnet myserver 33306
Trying 192.168.0.103...
Connected to myserver.
Escape character is '^]'.
b
5.5.5-10.1.13-MariaDB-1~jessie?gi[k+/?�fEb@VnKhK}Uomysql_native_passwordConnection closed by foreign host.
```
```
alex@myserver: telnet myserver 32769
Trying 192.168.0.103...
Connected to myserver.
Escape character is '^]'.
MONITOR
+OK
QUIT
+OK
Connection closed by foreign host.
```

**Comment by matejkramny** [comment]
This can be fixed by running

    create database semaphore;

Next beta / release will try to do this automatically. Thanks for reporting!

**Comment by alexrjs** [comment]
Hi.

Thanks for your help. Will try, today.

Cheers,
  Alex

**Comment by alexrjs** [comment]
Manual create of semaphore db worked. But... -setup still fails!

Setup:
```
alex@myserver:~/Downloads$ ./semaphore_linux_amd64 -setup

Hello, you will now be guided through a setup to:

- Set up configuration for a MySQL/MariaDB database
- Set up redis for session storage
- Set up a path for your playbooks
- Run DB Migrations
- Set up your user and password

DB Hostname (default 127.0.0.1:3306): myserver:33306
DB User (default root): 
DB Password: admin
DB Name (default semaphore): 
Redis Connection (default 127.0.0.1:6379): myserver:32774
Playbook path (will be auto-created if does not exist): 
Config:
{
	"mysql": {
		"host": "myserver:33306",
		"user": "root",
		"pass": "admin",
		"name": "semaphore"
	},
	"session_db": "myserver:32774",
	"mandrill": {
		"username": "",
		"password": ""
	},
	"port": "",
	"bugsnag_key": "",
	"tmp_path": "/tmp/semaphore"
}

Is this correct? (yes/no): yes
Running: mkdir -p /tmp/semaphore
Configuration written to /tmp/semaphore

Pinging database...
Pinging redis...
PING to redis unsuccessful
panic: dial tcp 127.0.0.1:6379: getsockopt: connection refused

goroutine 1 [running]:
panic(0xafe100, 0xc8201fa0f0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/ansible-semaphore/semaphore/database.RedisPing()
	/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/database/redis.go:25 +0x1af
main.doSetup(0x0)
	/Users/m/p/semaphore/main.go:132 +0xc32
main.main()
	/Users/m/p/semaphore/main.go:27 +0x30
2016/04/30 09:20:01 notifying bugsnag: dial tcp 127.0.0.1:6379: getsockopt: connection refused
2016/04/30 09:20:01 bugsnag.Notify: not notifying in development

```
But Redis answers:
```
alex@myserver:~/Downloads$ telnet myserver 32774
Trying 192.168.0.103...
Connected to myserver.
Escape character is '^]'.
MONITOR
+OK
QUIT
+OK

```

**Comment by alexrjs** [comment]
But this way works:
```
alex@myserver:~/Downloads$ ./semaphore_linux_amd64 -printConfig > config.json
alex@myserver:~/Downloads$ vi config.json 
alex@myserver:~/Downloads$ cat config.json 
{
	"mysql": {
		"host": "myserver:33306",
		"user": "root",
		"pass": "admin",
		"name": "semaphore"
	},
	"session_db": "myserver:32774",
	"mandrill": {
		"username": "",
		"password": ""
	},
	"port": ":3000",
	"bugsnag_key": "",
	"tmp_path": "/tmp/semaphore"
}
alex@myserver:~/Downloads$ ./semaphore_linux_amd64 -config config.json 
Semaphore 2.0-beta-2
Port :3000
MySQL root@myserver:33306 semaphore
Redis myserver:32774
Tmp Path (projects home) /tmp/semaphore
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /api/ping                 --> github.com/ansible-semaphore/semaphore/routes.Route.func1 (4 handlers)
[GIN-debug] POST   /api/auth/login           --> github.com/ansible-semaphore/semaphore/routes.login (5 handlers)
....

```

**Comment by alexrjs** [comment]
And it seems, that the user is not setup correct, since -setup was panicing...

```
...
[GIN] 2016/04/30 - 09:12:03 | 404 |       8.277µs | 127.0.0.1 |   GET     /favicon.ico
[GIN] 2016/04/30 - 09:12:03 | 404 |       3.719µs | 127.0.0.1 |   GET     /favicon.ico
[GIN] 2016/04/30 - 09:12:10 | 400 |    4.475902ms | 127.0.0.1 |   POST    /api/auth/login
2016/04/30 09:12:16 notifying bugsnag: Error 1146: Table 'semaphore.user' doesn't exist
2016/04/30 09:12:16 bugsnag.Notify: not notifying in development


2016/04/30 09:12:16 [Recovery] panic recovered:
POST /api/auth/login HTTP/1.1
Host: localhost:3000
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,it;q=0.2
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Cookie: semaphore=uW95nBPS_WYanIBQ3Yrz-La5mM0VvoR81narqVSYCII%3D
Origin: http://localhost:3000
Referer: http://localhost:3000/auth/login
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36


Error 1146: Table 'semaphore.user' doesn't exist
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42da79)
/Users/m/p/gospace/src/github.com/bugsnag/bugsnag-go/bugsnag.go:52 (0x513261)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:472 (0x45cd6e)
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 (0x42da79)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/login.go:48 (0x4b21c5)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51c31a)
/Users/m/p/gospace/src/github.com/ansible-semaphore/semaphore/routes/auth.go:96 (0x4b0a7f)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51c31a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/logger.go:66 (0x52dc4a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51c31a)
/Users/m/p/semaphore/main.go:74 (0x401b5f)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51c31a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/recovery.go:45 (0x52e9b1)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/context.go:97 (0x51c31a)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:284 (0x522f72)
/Users/m/p/gospace/src/github.com/gin-gonic/gin/gin.go:265 (0x522ba7)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:2081 (0x67ca9e)
/usr/local/Cellar/go/1.6/libexec/src/net/http/server.go:1472 (0x67934e)
/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 (0x45f421)
...
```

**Comment by matejkramny** [comment]
The setup didn't get to set up the user since it failed before it got to migrations.

From here you have two optinos:

1. Do setup again, enter same config parameters
2. Run the stuff below this

```
./semaphore -migrate
./semaphore -hash mypassword
... prints hash ...

manually insert it to semaphore.user table
```

**Comment by alexrjs** [comment]
Well,

-setup panicked, because it did not accept the myserver:32774 entry at the interactive setup. Even the config was listed perfectly. So I assume option 1. would fail the second time, also.

And I tried to add the semaphore.user by hand, did not work either since the table wasn’t created, either. „semaphore“ database had no tables at all. It was empty. I reviewed the code and couldn’t figure out how and where the database is set up.

Anyway, will try  your 2. options, to see if I can add the user after the -migrate.

Thanks for your support. 

Cheers,
   Alex

**Comment by matejkramny** [comment]
-migrate will create all the tables. After that, you can create a user.

I noticed from the logs of your -setup test, you left the redis connection question unchanged (meaning it defaulted to 127.0.0.1:6379).

Best,
Matej

**Comment by alexrjs** [comment]
Nope I didn't:

```
...
Redis Connection (default 127.0.0.1:6379): myserver:32774
...
```

:-)

**Comment by alexrjs** [comment]
2nd option worked, quite well.

```
alex@myserver:~/Downloads$ ./semaphore_linux_amd64 -config config.json -migrate
Semaphore 2.0-beta-2
Port :3000
MySQL root@myserver:33306 semaphore
Redis myserver:32774
Tmp Path (projects home) /tmp/semaphore

 Running DB Migrations
Creating migrations table
Executing migration v0.0.0 (at 2016-04-30 13:48:48.478721452 +0200 CEST)...
 [11/11]
Executing migration v1.0.0 (at 2016-04-30 13:48:51.866926479 +0200 CEST)...
 [7/7]
Executing migration v1.1.0 (at 2016-04-30 13:48:55.239536867 +0200 CEST)...
 [1/1]
Executing migration v1.2.0 (at 2016-04-30 13:48:55.95099266 +0200 CEST)...
 [1/1]
Executing migration v1.3.0 (at 2016-04-30 13:48:56.249713261 +0200 CEST)...
 [3/3]
Executing migration v1.4.0 (at 2016-04-30 13:48:58.602200968 +0200 CEST)...
 [2/2]
alex@myserver:~/Downloads$ 

alex@myserver:~/Downloads$ ./semaphore_linux_amd64 -config config.json -hash admin
Generated password:  $2a$11$XmoNkI6VFQQZbJQJeo1niuSBlfmxlYUuHIReX5a6VfoG4i6PbZACm

```
```
root@e4aec91ec930:/# mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.1.13-MariaDB-1~jessie mariadb.org binary distribution

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| semaphore          |
+--------------------+
4 rows in set (0.02 sec)

MariaDB [(none)]> use semaphore;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [semaphore]> show tables;
+----------------------------+
| Tables_in_semaphore        |
+----------------------------+
| access_key                 |
| event                      |
| migrations                 |
| project                    |
| project__environment       |
| project__inventory         |
| project__repository        |
| project__template          |
| project__template_schedule |
| project__user              |
| task                       |
| task__output               |
| user                       |
| user__token                |
+----------------------------+
14 rows in set (0.00 sec)

MariaDB [semaphore]> insert into user set name='admin', username='admin', email='admin@semaphore.local', password='$2a$11$XmoNkI6VFQQZbJQJeo1niuSBlfmxlYUuHIReX5a6VfoG4i6PbZACm', created=NOW()
    -> ;
Query OK, 1 row affected (0.02 sec)

MariaDB [semaphore]> 
```

**Comment by alexrjs** [comment]
Hi Matej.

All in all, the setup needs still some improvement. Yes you have to do only some manual steps, to fix the problems, but the experience could be more smooth for the final 2.0.

Anyway thanks for the quick response and the excelent support and investing your time in an alternative to ansible tower. And of course thanks for sharing your work.

Cheers,
   Alex

**Comment by matejkramny** [comment]
Next beta gets rid of redis and setup is much smoother :)

https://github.com/ansible-semaphore/semaphore/commit/b57cf04908637c8a57a3241ebac09f006d98e02e
