### ISSUE TITLE
Version 2.8.31 can't be started

### ISSUE THREAD

**Issue by ilikejam** [ansible-semaphore/semaphore#829]
Hi!

Looks like release 2.8.31 doesn't want to start with 'semaphore --config /path/to/json':

-----
semaphore@b5d37cb5364e:~$ /usr/bin/semaphore --config /etc/semaphore.json
Ansible Semaphore is a beautiful web UI for Ansible.
Source code is available at https://github.com/ansible-semaphore/semaphore.
Complete documentation is available at https://ansible-semaphore.com.

Usage:
  semaphore [flags]
  semaphore [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  migrate     Execute migrations
  service     Run Semaphore service
  setup       Perform interactive setup
  upgrade     Upgrade to latest stable version
  user        Manage users
  version     Print the version of Semaphore

Flags:
      --config string   Configuration file path
  -h, --help            help for semaphore

Use "semaphore [command] --help" for more information about a command.
-----

I can't see any doc changes, but did the startup args change since version 2.8.22?

**Comment by fiftin** [comment]
Please use `semaphore service --config /path/to/json`.

**Comment by fiftin** [comment]
Docs not updated, that's my fault.

**Comment by fiftin** [comment]
Perhaps the command `semaphore server` would be more understandable... I will add alias.

**Comment by bbc-davidstark** [comment]
Awesome. Working now!

Did the task template command-line options configuration box move as well? We run with '--tags' and '-l' set for some runs, but I can't see anywhere to specify those any more.

**Comment by OPSTime** [comment]
@fiftin v2.8.31, v2.8.30 image
When using docker image to start the service, the following error is reported:

```
......
Running db Migrations..
Checking db migrations


 > Username:  > Email: 
 Welcome back, admin! (a user with this username/email is already set up..)

 Re-launch this program pointing to the configuration file

./semaphore --config /etc/semaphore/config.json

 To run as daemon:

nohup ./semaphore --config /etc/semaphore/config.json &

 You can login with admin@localhost or admin.
Run Semaphore with semaphore --config /etc/semaphore/config.json
Ansible Semaphore is a beautiful web UI for Ansible.
Source code is available at https://github.com/ansible-semaphore/semaphore.
Complete documentation is available at https://ansible-semaphore.com.

Usage:
  semaphore [flags]
  semaphore [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  migrate     Execute migrations
  service     Run Semaphore service
  setup       Perform interactive setup
  upgrade     Upgrade to latest stable version
  user        Manage users
  version     Print the version of Semaphore

Flags:
      --config string   Configuration file path
  -h, --help            help for semaphore

Use "semaphore [command] --help" for more information about a command.
```

**Comment by OPSTime** [comment]
After using the old image to start the container, 'task template' and 'playbook repositories' cannot be accessed, and the following error is reported:

```
time="2022-01-24T16:19:14Z" level=error msg="gorp: no fields [git_branch] in type Repository"
goroutine 27 [running]:
runtime/debug.Stack(0xc000161008, 0x5f013e, 0xc0000ba1b8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/ansible-semaphore/semaphore/api/helpers.WriteError(0x187ac90, 0xc000341880, 0x1870120, 0xc001e0b3b0)
        /go/src/github.com/ansible-semaphore/semaphore/api/helpers/helpers.go:91 +0x191
github.com/ansible-semaphore/semaphore/api/projects.GetRepositories(0x187ac90, 0xc000341880, 0xc001e1a100)
        /go/src/github.com/ansible-semaphore/semaphore/api/projects/repository.go:74 +0x35d
net/http.HandlerFunc.ServeHTTP(0x17ec108, 0x187ac90, 0xc000341880, 0xc001e1a100)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1(0x187ac90, 0xc000341880, 0xc001e1a100)
        /go/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:41 +0x4a3
net/http.HandlerFunc.ServeHTTP(0xc001e0e648, 0x187ac90, 0xc000341880, 0xc001e1a100)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api.authentication.func1(0x187ac90, 0xc000341880, 0xc001e1a100)
        /go/src/github.com/ansible-semaphore/semaphore/api/auth.go:106 +0x667
net/http.HandlerFunc.ServeHTTP(0xc001e0e660, 0x187ac90, 0xc000341880, 0xc001e1a100)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1(0x187ac90, 0xc000341880, 0xc001e1a100)
        /go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0x131
net/http.HandlerFunc.ServeHTTP(0xc001e0e678, 0x187ac90, 0xc000341880, 0xc001e1a100)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1(0x187ac90, 0xc000341880, 0xc001e1a100)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:90 +0x122
net/http.HandlerFunc.ServeHTTP(0xc001e0ac00, 0x187ac90, 0xc000341880, 0xc001e1a100)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0x187ac90, 0xc000341880, 0xc001e1a100)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc001e02440, 0x187ac90, 0xc000341880, 0xc001e1a100)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000246180, 0x187ac90, 0xc000341880, 0xc000023900)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/gorilla/handlers.ProxyHeaders.func1(0x187ac90, 0xc000341880, 0xc000023900)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x114
net/http.HandlerFunc.ServeHTTP(0xc0000a3d88, 0x187ac90, 0xc000341880, 0xc000023900)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1(0x187ac90, 0xc000341880, 0xc000023900)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/service.go:26 +0x97
net/http.HandlerFunc.ServeHTTP(0xc0000a3da0, 0x187ac90, 0xc000341880, 0xc000023900)
        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0003400e0, 0x187ac90, 0xc000341880, 0xc000023900)
        /usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00017c140, 0x187c6a0, 0xc000166240)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b


time="2022-01-24T16:19:39Z" level=error msg="gorp: no fields [git_branch] in type Repository"
goroutine 42 [running]:
runtime/debug.Stack(0xc000245008, 0x5f013e, 0xc0000ba1b8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/ansible-semaphore/semaphore/api/helpers.WriteError(0x187ac90, 0xc000341dc0, 0x1870120, 0xc001def410)
        /go/src/github.com/ansible-semaphore/semaphore/api/helpers/helpers.go:91 +0x191
github.com/ansible-semaphore/semaphore/api/projects.GetRepositories(0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /go/src/github.com/ansible-semaphore/semaphore/api/projects/repository.go:74 +0x35d
net/http.HandlerFunc.ServeHTTP(0x17ec108, 0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1(0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /go/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:41 +0x4a3
net/http.HandlerFunc.ServeHTTP(0xc001e0ef18, 0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api.authentication.func1(0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /go/src/github.com/ansible-semaphore/semaphore/api/auth.go:106 +0x667
net/http.HandlerFunc.ServeHTTP(0xc001e0ef30, 0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1(0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /go/src/github.com/ansible-semaphore/semaphore/api/router.go:25 +0x131
net/http.HandlerFunc.ServeHTTP(0xc001e0ef48, 0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1(0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:90 +0x122
net/http.HandlerFunc.ServeHTTP(0xc001e0ba40, 0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc001e02980, 0x187ac90, 0xc000341dc0, 0xc001e1a600)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000246180, 0x187ac90, 0xc000341dc0, 0xc000023500)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/gorilla/handlers.ProxyHeaders.func1(0x187ac90, 0xc000341dc0, 0xc000023500)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x114
net/http.HandlerFunc.ServeHTTP(0xc0000a3d88, 0x187ac90, 0xc000341dc0, 0xc000023500)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1(0x187ac90, 0xc000341dc0, 0xc000023500)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/service.go:26 +0x97
net/http.HandlerFunc.ServeHTTP(0xc0000a3da0, 0x187ac90, 0xc000341dc0, 0xc000023500)
        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0003400e0, 0x187ac90, 0xc000341dc0, 0xc000023500)
        /usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0005c6a00, 0x187c6a0, 0xc000499a80)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b

```

**Comment by fiftin** [comment]
Unfortunately, it is correct behaviour. New version added column `git_branch` to Repository table. Old version of Semaphore can't work with this table anymore.

**Comment by OPSTime** [comment]
@fiftin 

**1、CMD in dockerfile should be updated, otherwise it cannot be started**
v2.8.33 image, docker-compose.yml add configuration：
command: [ "/usr/local/bin/semaphore-wrapper", "/usr/local/bin/semaphore", "server", "--config", "/etc/semaphore/config.json" ]

$ docker history ansiblesemaphore/semaphore:v2.8.30 --no-trunc
```
IMAGE                                                                     CREATED        CREATED BY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       SIZE      COMMENT
sha256:8f4ec70923d7884c43dfedde7db6101fd080f7f401220094187dcb062358bbd2   29 hours ago   /bin/sh -c #(nop)  CMD ["/usr/local/bin/semaphore-wrapper" "/usr/local/bin/semaphore" "--config" "/etc/semaphore/config.json"]   
```

$ docker history ansiblesemaphore/semaphore:v2.8.31 --no-trunc
```
IMAGE                                                                     CREATED        CREATED BY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       SIZE      COMMENT
sha256:09726a103a35a31776eb2c42d35a10a3f48f2dcd2971cc2bd614825701aee585   28 hours ago   /bin/sh -c #(nop)  CMD ["/usr/local/bin/semaphore-wrapper" "/usr/local/bin/semaphore" "--config" "/etc/semaphore/config.json"]
```

**2、Whether compatibility is considered, the program only takes the required field data from the DB.**
```
start 'v2 8.25 'version of semaphore：success
Start 'v2 8.31 'version of semaphore： failed, Dockerfile CMD error
Start 'v2 8.30 'version of semaphore： failed, Dockerfile CMD error
start 'v2 8.25 'version of semaphore：failed, error: "gorp: no fields [git_branch] in type Repository"
```

**Comment by OPSTime** [comment]
3、After upgrading to 'V2 8.33', task failed to run.Restore to normal after updating the key

10:18:56 AM
Task 6 added to queue
10:19:00 AM
Prepare task with template: dev_ansible-test
10:19:00 AM
Failed installing ssh key for repository access: cannot decrypt access key, perhaps encryption key was changed

**Comment by fiftin** [comment]
1. @OPSTime thank you very much, I missed this in Dockerfile!
2. We use ORM Gorp. This is how Gorp works: https://github.com/go-gorp/gorp/blob/80a2f4b08eacc7bb0951e062b66380d0a5a1e750/gorp.go#L301. I can't change this.  Perhaps I will add command like `semaphore rollback 2.8.25` to rollback migrations.
3. By the "Failed installing ssh key". It can be if you changed config.json (for example by running `semaphore setup`). In config file you can find field `access_key_encryption`. It used for encryption access keys in database.

**Comment by OPSTime** [comment]
3.I didn't change config JSON, I just changed a different image.

**Comment by fiftin** [comment]
Different image generates new `config.json`. Surely this is wrong behavior.
I see 2 solutions:
* disable encryption
* passing encryption key via environment variable

I will add the environment variable.

**Comment by mambon2** [comment]
Can you please fix the docker image.  It also doesn't startup after v2.8.33

**Comment by fiftin** [comment]
@mambon2 is progress.

**Comment by fiftin** [comment]
Done. 

@OPSTime, @mambon2 Please check v2.8.34.

@OPSTime You need to update your Docker image and add env variable `SEMAPHORE_ACCESS_KEY_ENCRYPTION`  with value generated by command:
```
head -c32 /dev/urandom | base64
```

After that you should resave your access keys:

<img width="300px" src="https://user-images.githubusercontent.com/914224/151123221-f8b1ff6d-33f6-4b7a-a6ed-c80074f190a9.png" />

**Comment by fiftin** [comment]
@bbc-davidstark

> Awesome. Working now!
> 
> Did the task template command-line options configuration box move as well? We run with '--tags' and '-l' set for some runs, but I can't see anywhere to specify those any more.

Please go to https://github.com/ansible-semaphore/semaphore/issues/832. We can discuss this functionality.
