### ISSUE TITLE
Unable to compile source

### ISSUE THREAD

**Issue by MrMEEE** [ansible-semaphore/semaphore#88]
When trying to compile the source code, I get:

[root@ansible semaphore-2.0-beta-2]# ./make.sh 
Creating util/bindata.go

/root/semaphore-2.0-beta-2/public/bundler.js:9
bundle.forEach(file => {
                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

What to do??

**Comment by matejkramny** [comment]
Whats your node.js version?

The bundler code uses some ES6 syntax
