### ISSUE TITLE
Unable to add ssh key

### ISSUE THREAD

**Issue by unclegaara** [ansible-semaphore/semaphore#893]
Hello guys! I got an error when trying to add ssh-private key into semaphore:
![Screenshot 2022-03-16 at 21 44 41](https://user-images.githubusercontent.com/4003953/158664549-6417756b-44ba-4881-afd7-00c8baeb8850.png)
Here is log message:
```
time="2022-03-16T18:45:03Z" level=error msg="crypto/aes: invalid key size 36"
goroutine 20 [running]:
runtime/debug.Stack(0xc00093ad20, 0x5ef5fe, 0xc000088218)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/ansible-semaphore/semaphore/api/helpers.WriteError(0x18b7ae0, 0xc0005b07e0, 0x18adac0, 0x1b85ee0)
	/go/src/github.com/ansible-semaphore/semaphore/api/helpers/helpers.go:92 +0x191
github.com/ansible-semaphore/semaphore/api/projects.AddKey(0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/go/src/github.com/ansible-semaphore/semaphore/api/projects/keys.go:91 +0x8ed
net/http.HandlerFunc.ServeHTTP(0x1827440, 0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api/projects.ProjectMiddleware.func1(0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/go/src/github.com/ansible-semaphore/semaphore/api/projects/project.go:41 +0x4a3
net/http.HandlerFunc.ServeHTTP(0xc000590b40, 0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api.authentication.func1(0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/go/src/github.com/ansible-semaphore/semaphore/api/auth.go:106 +0x667
net/http.HandlerFunc.ServeHTTP(0xc000590b58, 0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1(0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/go/src/github.com/ansible-semaphore/semaphore/api/router.go:23 +0x131
net/http.HandlerFunc.ServeHTTP(0xc000590b70, 0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1(0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:81 +0x182
net/http.HandlerFunc.ServeHTTP(0xc0005ad9c0, 0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.CORSMethodMiddleware.func1.1(0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc0005c28c0, 0x18b7ae0, 0xc0005b07e0, 0xc0005c5100)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00025e0c0, 0x18b7ae0, 0xc0005b07e0, 0xc0005c4f00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/gorilla/handlers.ProxyHeaders.func1(0x18b7ae0, 0xc0005b07e0, 0xc0005c4f00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x114
net/http.HandlerFunc.ServeHTTP(0xc000430c30, 0x18b7ae0, 0xc0005b07e0, 0xc0005c4f00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/ansible-semaphore/semaphore/cli/cmd.cropTrailingSlashMiddleware.func1(0x18b7ae0, 0xc0005b07e0, 0xc0005c4f00)
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0x97
net/http.HandlerFunc.ServeHTTP(0xc000430c48, 0x18b7ae0, 0xc0005b07e0, 0xc0005c4f00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0002562a0, 0x18b7ae0, 0xc0005b07e0, 0xc0005c4f00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000134000, 0x18b9600, 0xc000142000)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

App running in docker with postgresql database.

**Comment by fiftin** [comment]
Hi @unclegaara,

What Semaphore installation do you use?

**Comment by fiftin** [comment]
@unclegaara,

Looks like config option `access_key_encryption` has incorrect value.

Please read this https://docs.ansible-semaphore.com/administration-guide/security#database-encryption

**Comment by unclegaara** [comment]
@fiftin Yeah, that was the problem! Thank you so much!
