### ISSUE TITLE
Semaphore GUI error

### ISSUE THREAD

**Issue by jsinic** [ansible-semaphore/semaphore#921]
Hi

I have errors with running Semaphore GUI. Issue is present after update of Linux server. Running Ansible playbooks  over CLI works.

semaphore version
v2.8.53
ansible 2.9.27
python version = 3.6.8 

Do you have any advice how to solve this issue.

Error logs.

8:33:46 AM
Run TaskRunner with template: Windows_host_PING
8:33:46 AM
Unhandled error:
8:33:46 AM
Traceback (most recent call last):
8:33:46 AM
File "/root/snap/semaphore/common/ansible_env/lib/python3.6/site-packages/ansible/config/manager.py", line 605, in update_config_data
8:33:46 AM
value, origin = self.get_config_value_and_origin(config, configfile)
8:33:46 AM
File "/root/snap/semaphore/common/ansible_env/lib/python3.6/site-packages/ansible/config/manager.py", line 543, in get_config_value_and_origin
8:33:46 AM
value = ensure_type(value, defs[config].get('type'), origin=origin)
8:33:46 AM
File "/root/snap/semaphore/common/ansible_env/lib/python3.6/site-packages/ansible/config/manager.py", line 124, in ensure_type
8:33:46 AM
value = tempfile.mkdtemp(prefix=prefix, dir=value)
8:33:46 AM
File "/snap/semaphore/183/usr/lib/python3.6/tempfile.py", line 509, in mkdtemp
8:33:46 AM
_os.mkdir(file, 0o700)
8:33:46 AM
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ansible-local-1228101q_99tt2q'

**Comment by fiftin** [comment]
Hi @jsinic ,

Semaphore (installed via Snap) uses its own ansible and python. It is looks like a bug...
